import Mathlib.Data.Int.Basic
import Mathlib.Data.List.Basic

abbrev TruncQSeries := List ℤ

def coeff (f : TruncQSeries) (n : ℕ) : ℤ := f.getD n 0
def zero (len : ℕ) : TruncQSeries := List.replicate len 0
def one (len : ℕ) : TruncQSeries := 1 :: List.replicate (len - 1) 0

def mul (f g : TruncQSeries) (len : ℕ) : TruncQSeries :=
  List.ofFn fun k : Fin len =>
    (List.range (k.val + 1)).foldl
      (fun acc j => acc + coeff f j * coeff g (k.val - j)) 0

def invHelper (A : List ℤ) : ℕ → List ℤ
  | 0 => []
  | 1 => [1]
  | (m + 1) =>
    let B := invHelper A m
    let s := (List.range m).foldl (fun acc k => acc + (A.getD (k + 1) 0) * (B.getD (m - 1 - k) 0)) 0
    B ++ [-s]

def inv (f : TruncQSeries) (len : ℕ) : TruncQSeries := invHelper f len

def pow (f : TruncQSeries) (n : ℕ) (len : ℕ) : TruncQSeries :=
  match n with
  | 0 => one len
  | (k + 1) => mul f (pow f k len) len

def base_eta (len : ℕ) : TruncQSeries :=
  List.ofFn fun i : Fin len =>
    let p1 := fun (k : ℤ) => k * (3 * k - 1) / 2
    let p2 := fun (k : ℤ) => k * (3 * k + 1) / 2
    -- We need to find if i.val is generated by p1(k) or p2(k) for some k>=0
    -- This is slightly tricky to do cleanly in a simple list comprehension without loops.
    -- Let's just do a naive check up to len.
    let ks := List.range (len + 1)
    let k_pos := ks.find? (fun k => p1 k == (i.val : ℤ))
    let k_neg := ks.find? (fun k => k > 0 ∧ p2 k == (i.val : ℤ))
    match k_pos, k_neg with
    | some k, _ => if k % 2 == 0 then 1 else -1
    | _, some k => if k % 2 == 0 then 1 else -1
    | _, _ => 0

#eval inv (base_eta 10) 10
