import DualScale.NS.HypothesisU
import DualScale.NS.Basic
import DualScale.SpectralGap.Basic
import DualScale.CFM.Basic
import DualScale.Phase.Basic
import DualScale.K3Lock.Basic
import DualScale.SusyBreaking.Basic
import DualScale.Discovery.Notebook3
import DualScale.Discovery.Notebook1
