import DualScale.NS.HypothesisU
import DualScale.NS.Basic
import DualScale.SpectralGap.Basic
import DualScale.CFM.Basic
import DualScale.Phase.Basic
import DualScale.K3Lock.Basic
import DualScale.SusyBreaking.Basic
import DualScale.Discovery.Notebook3
import DualScale.Discovery.Notebook1
import DualScale.QSeries.Basic
import DualScale.QSeries.EtaQuotient
import DualScale.QSeries.MockTheta
import DualScale.QSeries.ModularTransform
import DualScale.Asymptotics.Rademacher
import DualScale.Asymptotics.SaddlePoint
import DualScale.Asymptotics.BPSEntropy
import DualScale.Asymptotics.Batch547
import DualScale.Geometry.PicardFuchs
import DualScale.Geometry.TDuality
import DualScale.Physics.Enstrophy
import DualScale.Physics.AubinLions
import DualScale.Physics.SpectralGap
import DualScale.Physics.CFMVortex
import DualScale.Physics.PhaseTransition
import DualScale.Physics.DyadicShell
import DualScale.Physics.MasterDualScale
