-- Auto-generated by tools/gen_batch_547.py
import DualScale.QSeries.EtaQuotient
import DualScale.Asymptotics.BPSEntropy

namespace DualScale.Asymptotics.Batch
open DualScale.QSeries.EtaQuotient

def d_e46d9956_a9e : EtaQuot := ⟨[(10, 2)]⟩
def d_d08c97f0_c08 : EtaQuot := ⟨[(11, -4)]⟩
def d_116e8203_b81 : EtaQuot := ⟨[(3, 3)]⟩
def d_5312c21c_e52 : EtaQuot := ⟨[(6, 2)]⟩
def d_8317b09b_72e : EtaQuot := ⟨[(6, 1)]⟩
def d_eb03f21e_c0a : EtaQuot := ⟨[(3, 4)]⟩
def d_e10679e2_442 : EtaQuot := ⟨[(10, 3)]⟩
def d_f0d9021e_053 : EtaQuot := ⟨[(10, 3)]⟩
def d_a626695f_1b1 : EtaQuot := ⟨[(4, 1)]⟩
def d_ade3259b_76b : EtaQuot := ⟨[(11, -3)]⟩
def d_900bb087_3e5 : EtaQuot := ⟨[(11, -4)]⟩
def d_579d5934_bc6 : EtaQuot := ⟨[(11, -3)]⟩
def d_c222ac5c_515 : EtaQuot := ⟨[(8, 2)]⟩
def d_5c01cd04_5f8 : EtaQuot := ⟨[(10, 1)]⟩
def d_2222e5b4_b6d : EtaQuot := ⟨[(11, -1)]⟩
def d_522b77ed_d01 : EtaQuot := ⟨[(9, -1)]⟩
def d_6c45da89_243 : EtaQuot := ⟨[(6, 3)]⟩
def d_77ead353_8d8 : EtaQuot := ⟨[(3, 3), (8, 2)]⟩
def d_2c70cfff_714 : EtaQuot := ⟨[(8, 4)]⟩
def d_930fe7cb_01c : EtaQuot := ⟨[(10, 4)]⟩
def d_807208fe_d33 : EtaQuot := ⟨[(4, 1)]⟩
def d_42763ef0_03b : EtaQuot := ⟨[(3, 1)]⟩
def d_89968a81_e4c : EtaQuot := ⟨[(10, -2)]⟩
def d_88746e42_d74 : EtaQuot := ⟨[(8, 2), (3, 2)]⟩
def d_50a39513_894 : EtaQuot := ⟨[(8, 1)]⟩
def d_39c56088_623 : EtaQuot := ⟨[(1, 1), (6, -1)]⟩
def d_bbb9ebf8_2f1 : EtaQuot := ⟨[(9, 0)]⟩
def d_e87a636f_27a : EtaQuot := ⟨[(3, 3), (7, -3)]⟩
def d_56f1cf6b_bfd : EtaQuot := ⟨[(8, 3)]⟩
def d_750e49ec_8cf : EtaQuot := ⟨[(10, 3)]⟩
def d_69ad9c99_0ec : EtaQuot := ⟨[(5, 1)]⟩
def d_7859bd56_029 : EtaQuot := ⟨[(6, 2)]⟩
def d_b4a25fbe_b90 : EtaQuot := ⟨[(1, 1)]⟩
def d_e56fdf39_8e3 : EtaQuot := ⟨[(10, -1)]⟩
def d_5ea9e681_cd7 : EtaQuot := ⟨[(12, -1), (3, 3)]⟩
def d_30466116_cce : EtaQuot := ⟨[(8, 2)]⟩
def d_e64fad96_dbd : EtaQuot := ⟨[(9, 1)]⟩
def d_38bd5146_d75 : EtaQuot := ⟨[(8, 1), (11, -3)]⟩
def d_1ec02312_96d : EtaQuot := ⟨[(3, -1)]⟩
def d_f2841284_167 : EtaQuot := ⟨[(10, 1)]⟩
def d_801f5539_45c : EtaQuot := ⟨[(12, 1)]⟩
def d_745150f7_f49 : EtaQuot := ⟨[(3, 4), (7, -2)]⟩
def d_f59ff17a_3f9 : EtaQuot := ⟨[(8, 1)]⟩
def d_50156515_4e0 : EtaQuot := ⟨[(9, -1)]⟩
def d_41b228df_f54 : EtaQuot := ⟨[(8, 1)]⟩
def d_f963b410_c6d : EtaQuot := ⟨[(10, 1)]⟩
def d_b8d896c2_e08 : EtaQuot := ⟨[(12, -4)]⟩
def d_ddcbfe4d_c08 : EtaQuot := ⟨[(8, 3)]⟩
def d_fe5e3852_880 : EtaQuot := ⟨[(10, 7)]⟩
def d_ec2c7e82_933 : EtaQuot := ⟨[(11, -4)]⟩
def d_fe943483_5cb : EtaQuot := ⟨[(5, 1), (9, -1)]⟩
def d_f2ec2a4c_70e : EtaQuot := ⟨[(6, 4)]⟩
def d_812699f3_648 : EtaQuot := ⟨[(10, 3), (11, -3)]⟩
def d_12fc5cc3_898 : EtaQuot := ⟨[(11, -3)]⟩
def d_f85e401e_a54 : EtaQuot := ⟨[(12, 3)]⟩
def d_efeb392e_85d : EtaQuot := ⟨[(9, -2)]⟩
def d_a9dd1cb0_200 : EtaQuot := ⟨[(9, -4)]⟩
def d_ae4ef401_c35 : EtaQuot := ⟨[(7, -3)]⟩
def d_08f66605_55a : EtaQuot := ⟨[(3, 2)]⟩
def d_6ad95fd7_f1a : EtaQuot := ⟨[(8, 1), (7, -1)]⟩
def d_66eaa844_98c : EtaQuot := ⟨[(4, 1)]⟩
def d_bed15f16_486 : EtaQuot := ⟨[(8, 3), (3, 2)]⟩
def d_f08a40c0_512 : EtaQuot := ⟨[(6, -2)]⟩
def d_ce501bca_5ca : EtaQuot := ⟨[(4, 2)]⟩
def d_bd190d53_83d : EtaQuot := ⟨[(11, -2)]⟩
def d_cece679e_ac4 : EtaQuot := ⟨[(8, 4), (6, 1)]⟩
def d_56e6734f_20e : EtaQuot := ⟨[(11, -4), (10, 2)]⟩
def d_aacf173f_0bb : EtaQuot := ⟨[(4, 3), (7, 1)]⟩
def d_dbde6529_bbe : EtaQuot := ⟨[(8, 2), (11, -1)]⟩
def d_6b01415e_129 : EtaQuot := ⟨[(9, -3)]⟩
def d_cec364ba_2c0 : EtaQuot := ⟨[(10, 2)]⟩
def d_2120dc71_a26 : EtaQuot := ⟨[(11, 1)]⟩
def d_018e5fb8_cd2 : EtaQuot := ⟨[(8, 3), (3, 3)]⟩
def d_7e5b2734_36a : EtaQuot := ⟨[(7, -1)]⟩
def d_ac4e5a72_b2a : EtaQuot := ⟨[(7, 4)]⟩
def d_6477185c_a81 : EtaQuot := ⟨[(9, -4), (6, 4)]⟩
def d_a3870b15_f0f : EtaQuot := ⟨[(3, 1)]⟩
def d_fd18f387_1aa : EtaQuot := ⟨[(8, 2), (3, 3)]⟩
def d_4305c607_22f : EtaQuot := ⟨[(9, -4)]⟩
def d_75f7007a_c3c : EtaQuot := ⟨[(8, 1), (11, -2)]⟩
def d_67522507_22c : EtaQuot := ⟨[(9, -3), (10, 4)]⟩
def d_efdfea04_6e7 : EtaQuot := ⟨[(8, 1), (10, 1)]⟩
def d_2465e716_53b : EtaQuot := ⟨[(11, -5)]⟩
def d_0d571bf0_87e : EtaQuot := ⟨[(9, -3), (7, -2)]⟩
def d_a000b0b3_978 : EtaQuot := ⟨[(9, -2)]⟩
def d_df9101f7_1d7 : EtaQuot := ⟨[(10, 3), (11, -4)]⟩
def d_3f4c1c45_a3f : EtaQuot := ⟨[(7, -2)]⟩
def d_5b559f6e_2de : EtaQuot := ⟨[(12, 1)]⟩
def d_511acd39_b3f : EtaQuot := ⟨[(12, 0)]⟩
def d_225b3519_de0 : EtaQuot := ⟨[(11, -1)]⟩
def d_10ae0f97_027 : EtaQuot := ⟨[(1, 1)]⟩
def d_e1137acf_1f4 : EtaQuot := ⟨[(1, 1)]⟩
def d_9ac48c46_e40 : EtaQuot := ⟨[(11, -3)]⟩
def d_a957382c_6a7 : EtaQuot := ⟨[(4, 3)]⟩
def d_3b2e12e5_827 : EtaQuot := ⟨[(3, -1)]⟩
def d_58d68cc8_e04 : EtaQuot := ⟨[(8, 4)]⟩
def d_fdd56268_fdd : EtaQuot := ⟨[(5, 2), (6, 3)]⟩
def d_8eada35c_967 : EtaQuot := ⟨[(10, 2)]⟩
def d_b196d58b_db6 : EtaQuot := ⟨[(10, 2)]⟩
def d_18335d39_495 : EtaQuot := ⟨[(11, -4)]⟩
def d_897c7e44_491 : EtaQuot := ⟨[(8, 3)]⟩
def d_362f8f36_239 : EtaQuot := ⟨[(11, -4)]⟩
def d_33e70480_9f1 : EtaQuot := ⟨[(3, -1)]⟩
def d_c214435f_712 : EtaQuot := ⟨[(9, 0)]⟩
def d_093ff446_116 : EtaQuot := ⟨[(3, 0)]⟩
def d_c066b0fd_33b : EtaQuot := ⟨[(8, 3), (11, -4)]⟩
def d_5e7bd84d_8e1 : EtaQuot := ⟨[(3, -1), (6, 1)]⟩
def d_4caaffa8_2cc : EtaQuot := ⟨[(4, 1)]⟩
def d_c1271795_0f1 : EtaQuot := ⟨[(12, 2)]⟩
def d_ad3c0af3_aa8 : EtaQuot := ⟨[(8, 2)]⟩
def d_b650b655_b20 : EtaQuot := ⟨[(6, 2)]⟩
def d_b716e171_1b1 : EtaQuot := ⟨[(12, -3)]⟩
def d_e1721e19_b24 : EtaQuot := ⟨[(7, -4)]⟩
def d_17e2046a_d97 : EtaQuot := ⟨[(7, -2)]⟩
def d_5d25b144_c8b : EtaQuot := ⟨[(10, -1)]⟩
def d_a40d2329_b35 : EtaQuot := ⟨[(3, 2)]⟩
def d_20809c7a_ebe : EtaQuot := ⟨[(9, -5)]⟩
def d_2373a720_678 : EtaQuot := ⟨[(1, 1), (10, 3)]⟩
def d_6a04df73_39b : EtaQuot := ⟨[(11, -1)]⟩
def d_2b7437f4_cb0 : EtaQuot := ⟨[(12, -1)]⟩
def d_c918769f_df4 : EtaQuot := ⟨[(12, -2)]⟩
def d_be14b34f_3ed : EtaQuot := ⟨[(10, 4), (1, 1)]⟩
def d_9aa3298c_873 : EtaQuot := ⟨[(12, 0)]⟩
def d_77797445_058 : EtaQuot := ⟨[(7, -2)]⟩
def d_bbec07e9_478 : EtaQuot := ⟨[(4, 2), (9, -3)]⟩
def d_03afe907_92d : EtaQuot := ⟨[(6, 4)]⟩
def d_ab778e8d_fe0 : EtaQuot := ⟨[(4, 1)]⟩
def d_3cf846a2_ecb : EtaQuot := ⟨[(7, 2)]⟩
def d_44160a41_442 : EtaQuot := ⟨[(8, 0)]⟩
def d_0fe846a0_6ca : EtaQuot := ⟨[(11, -4)]⟩
def d_3fd8258b_3f7 : EtaQuot := ⟨[(8, 0), (3, 2)]⟩
def d_051c1a80_af4 : EtaQuot := ⟨[(10, 1)]⟩
def d_86315bef_f2d : EtaQuot := ⟨[(12, 0)]⟩
def d_1096b813_205 : EtaQuot := ⟨[(10, 2)]⟩
def d_074d5adf_6a1 : EtaQuot := ⟨[(3, 2), (7, -2)]⟩
def d_c13073d7_887 : EtaQuot := ⟨[(12, 1)]⟩
def d_73009d11_5c1 : EtaQuot := ⟨[(10, 4)]⟩
def d_2083fa6e_5e5 : EtaQuot := ⟨[(10, 1), (11, -10)]⟩
def d_8247d35d_0aa : EtaQuot := ⟨[(3, -1), (10, 4)]⟩
def d_8c7b2fcc_d2b : EtaQuot := ⟨[(8, 2), (3, 3)]⟩
def d_0fad0338_34f : EtaQuot := ⟨[(6, 4)]⟩
def d_589d7cd8_6f0 : EtaQuot := ⟨[(9, -4), (7, -4)]⟩
def d_d742407c_a77 : EtaQuot := ⟨[(4, 2), (7, 3)]⟩
def d_e41e7b9a_3ff : EtaQuot := ⟨[(12, 2)]⟩
def d_fd708092_b5a : EtaQuot := ⟨[(6, 2)]⟩
def d_df009970_ff7 : EtaQuot := ⟨[(11, -1)]⟩
def d_32951d33_edc : EtaQuot := ⟨[(11, -4)]⟩
def d_3c604c7c_4e7 : EtaQuot := ⟨[(11, -3)]⟩
def d_14015f45_de8 : EtaQuot := ⟨[(4, 1)]⟩
def d_64c52d82_f40 : EtaQuot := ⟨[(12, -2)]⟩
def d_d701af84_874 : EtaQuot := ⟨[(11, -1)]⟩
def d_f3243490_113 : EtaQuot := ⟨[(7, 1)]⟩
def d_722de966_57a : EtaQuot := ⟨[(4, 2)]⟩
def d_70ceee0c_b6d : EtaQuot := ⟨[(6, 1)]⟩
def d_df27c3a6_9e2 : EtaQuot := ⟨[(11, -4)]⟩
def d_40c1e7b1_72d : EtaQuot := ⟨[(3, 1)]⟩
def d_bd173cf3_fc6 : EtaQuot := ⟨[(4, 2), (11, -5)]⟩
def d_3a95b16b_a0c : EtaQuot := ⟨[(11, -2)]⟩
def d_37f321ff_efe : EtaQuot := ⟨[(10, 6)]⟩
def d_a50e763b_330 : EtaQuot := ⟨[(12, 4)]⟩
def d_924813bb_4e4 : EtaQuot := ⟨[(9, -4)]⟩
def d_6da4ef51_ea9 : EtaQuot := ⟨[(11, -3), (8, 3)]⟩
def d_d50fe234_206 : EtaQuot := ⟨[(9, -2)]⟩
def d_95400537_156 : EtaQuot := ⟨[(9, -4)]⟩
def d_793a01a8_709 : EtaQuot := ⟨[(9, 0)]⟩
def d_f3f4f87c_bc9 : EtaQuot := ⟨[(8, 1)]⟩
def d_f4ed7e6d_788 : EtaQuot := ⟨[(9, 1), (4, 1)]⟩
def d_b7e44971_ca3 : EtaQuot := ⟨[(4, 3)]⟩
def d_a8bd9932_2dc : EtaQuot := ⟨[(3, -1)]⟩
def d_77b5cb53_8bb : EtaQuot := ⟨[(8, 2), (3, 2)]⟩
def d_095dea1c_5e6 : EtaQuot := ⟨[(12, -1)]⟩
def d_780b190f_6b1 : EtaQuot := ⟨[(9, -3)]⟩
def d_91130e03_a15 : EtaQuot := ⟨[(6, 3)]⟩
def d_ce2c3ecb_890 : EtaQuot := ⟨[(7, 1)]⟩
def d_31e08508_592 : EtaQuot := ⟨[(8, 1), (9, -1)]⟩
def d_5a9fdf90_464 : EtaQuot := ⟨[(9, -2)]⟩
def d_b9b92dc8_af1 : EtaQuot := ⟨[(11, -3)]⟩
def d_1391e369_4c2 : EtaQuot := ⟨[(8, -1)]⟩
def d_e1fb1c00_6ef : EtaQuot := ⟨[(8, -1)]⟩
def d_b2b3c861_bac : EtaQuot := ⟨[(11, -3)]⟩
def d_81f07814_708 : EtaQuot := ⟨[(6, 0)]⟩
def d_f77df2fb_53a : EtaQuot := ⟨[(12, 2)]⟩
def d_db864376_5cf : EtaQuot := ⟨[(11, -2)]⟩
def d_59544080_71b : EtaQuot := ⟨[(8, 3), (9, -3)]⟩
def d_60305155_31f : EtaQuot := ⟨[(11, -1)]⟩
def d_85bb1fb0_f79 : EtaQuot := ⟨[(3, 2)]⟩
def d_8133c06a_c45 : EtaQuot := ⟨[(3, 2), (7, -2), (10, 1), (11, -4), (12, -1)]⟩
def d_bfb39e30_fdd : EtaQuot := ⟨[(6, 3), (8, 3), (11, -10), (12, -12)]⟩
def d_4db0fa68_696 : EtaQuot := ⟨[(3, -1), (9, 2), (11, -2), (12, 4), (7, 4), (2, 1)]⟩
def d_29a5b3f7_42e : EtaQuot := ⟨[(1, 1), (8, 2), (10, 3), (11, -2), (12, 7)]⟩
def d_adc70aed_54d : EtaQuot := ⟨[(10, 4), (11, -7), (12, -13)]⟩
def d_bf3ae8b2_757 : EtaQuot := ⟨[(1, 1), (10, 1), (7, 1), (11, -1)]⟩
def d_c976750b_d61 : EtaQuot := ⟨[(8, 4), (11, -12), (10, -1), (3, -1)]⟩
def d_2fc91a15_dcf : EtaQuot := ⟨[(4, 2), (5, 2), (8, 3), (11, -2)]⟩
def d_6bbd4610_2a8 : EtaQuot := ⟨[(9, -3), (11, -12)]⟩
def d_e5dbbecc_765 : EtaQuot := ⟨[(4, 2), (6, -2), (11, -2)]⟩
def d_bf9a9dca_0d9 : EtaQuot := ⟨[(2, 1), (3, -1), (7, 1), (11, -10), (12, -5)]⟩
def d_dd560ed8_386 : EtaQuot := ⟨[(3, -1), (4, 1), (12, 3)]⟩
def d_e226ac03_e0e : EtaQuot := ⟨[(11, -4), (4, 1), (12, 1)]⟩
def d_119ff014_ca3 : EtaQuot := ⟨[(7, -1), (8, 3), (9, -2), (11, -2)]⟩
def d_59682fd3_b4b : EtaQuot := ⟨[(8, 4), (9, -4), (10, 3), (11, -4)]⟩
def d_a008ab76_722 : EtaQuot := ⟨[(2, -1), (4, 4), (9, -4), (6, -1)]⟩
def d_d17a0c31_b88 : EtaQuot := ⟨[(4, 3), (5, 3), (6, -1), (9, 3), (11, -12)]⟩
def d_1ee0292f_39d : EtaQuot := ⟨[(6, 4), (8, 2), (10, 4)]⟩
def d_2b854b05_68a : EtaQuot := ⟨[(4, -1), (6, 4), (7, -3), (9, 1), (12, 4)]⟩
def d_21657e29_db8 : EtaQuot := ⟨[(7, -2), (8, 4), (9, -1), (10, 4), (12, 2)]⟩
def d_50e5f4ec_703 : EtaQuot := ⟨[(9, -4), (11, -3), (12, 24), (10, 1)]⟩
def d_936c26e3_9d6 : EtaQuot := ⟨[(7, -2), (8, 4), (9, -4), (11, -12), (12, -12)]⟩
def d_1387a909_b1d : EtaQuot := ⟨[(4, 4), (6, 4), (10, 24), (11, -4)]⟩
def d_de3d7fb0_1c9 : EtaQuot := ⟨[(10, 2), (11, -2), (12, -20)]⟩
def d_7369d269_b7f : EtaQuot := ⟨[(9, -4), (11, -4), (7, -4)]⟩
def d_fc8ee452_fe7 : EtaQuot := ⟨[(8, 2), (10, 4), (11, -1)]⟩
def d_121ae14d_3b0 : EtaQuot := ⟨[(9, -3), (10, 3), (11, -3)]⟩
def d_6a04ac9a_f92 : EtaQuot := ⟨[(6, 3), (9, -2), (11, -8), (12, 2), (3, 1)]⟩
def d_c85c4e6f_a1f : EtaQuot := ⟨[(10, 4), (1, 1), (8, 2)]⟩
def d_7a85eb77_5da : EtaQuot := ⟨[(8, 3), (12, 24), (3, 2)]⟩
def d_6168297d_9a4 : EtaQuot := ⟨[(8, 1), (10, 1), (12, 24), (9, -1)]⟩
def d_be8820f4_8b9 : EtaQuot := ⟨[(6, 3), (11, -4)]⟩
def d_41c80361_060 : EtaQuot := ⟨[(8, 4)]⟩
def d_3c1aab06_1af : EtaQuot := ⟨[(8, 3), (10, 2), (4, 2), (7, 4)]⟩
def d_91c74c5b_ce1 : EtaQuot := ⟨[(3, 2), (7, -2), (9, -3), (10, 3), (11, -3)]⟩
def d_83e58168_c40 : EtaQuot := ⟨[(6, 2), (8, 3), (11, -6), (12, -4)]⟩
def d_dc54778a_5f2 : EtaQuot := ⟨[(3, 3), (7, -2), (11, -4)]⟩
def d_85e34eaf_849 : EtaQuot := ⟨[(3, 1), (4, 1), (8, 2), (10, 1)]⟩
def d_2cb209d2_442 : EtaQuot := ⟨[(3, 1), (5, 1), (7, -4), (10, 2)]⟩
def d_9cbfe2b9_3a0 : EtaQuot := ⟨[(3, 1), (4, -1), (7, -4), (8, 2)]⟩
def d_bf272fb0_6f0 : EtaQuot := ⟨[(8, 1), (3, 1), (12, -3)]⟩
def d_469350b0_bec : EtaQuot := ⟨[(8, 4), (10, 4), (12, 25), (1, 1)]⟩
def d_ddd6ec45_563 : EtaQuot := ⟨[(8, 2), (9, -4), (12, 2), (10, 2)]⟩
def d_ea7674a8_ea3 : EtaQuot := ⟨[(7, -4), (8, 4), (9, -2), (11, -3), (3, 1)]⟩
def d_1cf84b58_cef : EtaQuot := ⟨[(7, -4), (8, -2), (9, -4), (11, -3), (12, 1)]⟩
def d_17a2edd3_88a : EtaQuot := ⟨[(9, -3), (10, 10), (11, -4), (12, -1)]⟩
def d_43b8f006_e10 : EtaQuot := ⟨[(10, 1), (12, 4), (5, -1), (11, -4)]⟩
def d_a07c8df3_6fa : EtaQuot := ⟨[(3, 4), (4, 1), (11, -3), (12, 26)]⟩
def d_ccde8145_9a4 : EtaQuot := ⟨[(11, -12), (4, 2), (7, -2)]⟩
def d_ebcfe97c_c1a : EtaQuot := ⟨[(8, -1), (10, 8), (11, -3)]⟩
def d_593f3788_d1d : EtaQuot := ⟨[(1, 2), (5, 1), (10, 1), (12, 1)]⟩
def d_e66d6af7_699 : EtaQuot := ⟨[(6, 4), (8, 4), (10, 5), (11, -2)]⟩
def d_43078c46_6c9 : EtaQuot := ⟨[(8, 2), (3, 3)]⟩
def d_26d3c458_eab : EtaQuot := ⟨[(7, -4), (10, 4), (11, -12)]⟩
def d_3228531e_77a : EtaQuot := ⟨[(5, 1), (10, 4), (12, 4), (11, -2)]⟩
def d_56d94be4_0ee : EtaQuot := ⟨[(4, -1), (5, -4), (7, -4), (8, 4), (10, 24)]⟩
def d_5e687edc_4af : EtaQuot := ⟨[(9, -2), (11, -4), (6, -3), (1, 1)]⟩
def d_156b01cc_9ee : EtaQuot := ⟨[(9, -3), (10, 4), (11, -2), (12, -21)]⟩
def d_2d574c50_dca : EtaQuot := ⟨[(9, -1), (6, 3), (8, 2)]⟩
def d_9751e15d_591 : EtaQuot := ⟨[(6, -1), (8, 2), (12, -7)]⟩
def d_68c44b9d_401 : EtaQuot := ⟨[(3, 1), (5, 1), (7, -4), (11, -4), (12, -2)]⟩
def d_f74df779_0d4 : EtaQuot := ⟨[(6, 1), (9, -2), (10, 5)]⟩
def d_2bf837ce_46f : EtaQuot := ⟨[(4, 1), (5, 2), (10, 2)]⟩
def d_eaf90f0c_184 : EtaQuot := ⟨[(8, 12), (4, 6), (7, 1)]⟩
def d_c37b1b73_f3a : EtaQuot := ⟨[(6, -1), (8, 2), (9, -2), (10, 5), (11, -3)]⟩
def d_cd9cc228_3ef : EtaQuot := ⟨[(7, -4), (10, 9), (11, -3)]⟩
def d_e768bbc1_ed1 : EtaQuot := ⟨[(3, 1), (5, 1), (6, 4), (10, 4)]⟩
def d_e43a0d0c_18d : EtaQuot := ⟨[(6, 4), (9, -3), (10, 4), (11, -4)]⟩
def d_56e0c99e_f51 : EtaQuot := ⟨[(6, 1), (8, 4), (10, 3), (11, -12), (12, -1)]⟩
def d_2a5c6f14_c5a : EtaQuot := ⟨[(10, 4), (11, -4)]⟩
def d_e282a73f_f6e : EtaQuot := ⟨[(4, 4), (6, -1), (7, 2), (8, 3), (10, 2)]⟩
def d_c0c9506b_f15 : EtaQuot := ⟨[(3, 1), (6, 1), (7, -2), (8, 2), (10, 2)]⟩
def d_d36e8bab_bbd : EtaQuot := ⟨[(5, -1), (6, -1), (10, 4), (11, -4), (12, -12)]⟩
def d_31c5b286_2ee : EtaQuot := ⟨[(8, 1), (10, 1), (4, 1)]⟩
def d_2fc3242e_695 : EtaQuot := ⟨[(8, -1), (1, 2), (3, -1)]⟩
def d_ca4b1078_339 : EtaQuot := ⟨[(7, -4), (9, -2), (11, -1), (12, -2)]⟩
def d_480cd210_167 : EtaQuot := ⟨[(5, 2), (6, 4), (10, 8), (12, 4)]⟩
def d_978bf7f4_a62 : EtaQuot := ⟨[(3, 2), (6, 2), (7, -2)]⟩
def d_916b04e6_f7f : EtaQuot := ⟨[(1, 1), (7, 1), (10, 2), (12, 2)]⟩
def d_5101c34d_d92 : EtaQuot := ⟨[(8, 1), (3, 2), (7, -4), (10, 1)]⟩
def d_a3bb37bb_3d0 : EtaQuot := ⟨[(11, -4), (3, 2), (10, 2)]⟩
def d_ad0bb270_a8c : EtaQuot := ⟨[(6, 2), (8, 2), (10, 4), (11, -6)]⟩
def d_b02d427d_9cd : EtaQuot := ⟨[(9, -4), (6, 2), (7, -2)]⟩
def d_24b8c0b1_c31 : EtaQuot := ⟨[(5, 1), (6, 1), (11, -1)]⟩
def d_0232e77f_e19 : EtaQuot := ⟨[(10, 2)]⟩
def d_05e14f40_a08 : EtaQuot := ⟨[(2, 2), (3, -1), (8, -4), (9, 3), (11, -1)]⟩
def d_d1e19db1_152 : EtaQuot := ⟨[(9, -3), (10, 3), (3, 1)]⟩
def d_65202556_fff : EtaQuot := ⟨[(8, 1), (11, -8), (12, -11)]⟩
def d_8f958e6d_d96 : EtaQuot := ⟨[(6, 3), (7, -2), (8, 4), (11, -4), (12, 3), (9, -4)]⟩
def d_ac221f84_3fe : EtaQuot := ⟨[(1, 1), (10, 5)]⟩
def d_3853cea6_ffb : EtaQuot := ⟨[(6, 4), (8, 4), (10, 2), (3, 1)]⟩
def d_e1abc581_918 : EtaQuot := ⟨[(3, 2), (5, 1), (6, 3), (7, -2), (8, 3), (12, -1)]⟩
def d_713ab765_30e : EtaQuot := ⟨[(8, 8), (9, -4)]⟩
def d_5762e4f6_781 : EtaQuot := ⟨[(8, 4), (9, -4), (11, -4), (12, 3)]⟩
def d_7ba0491a_bae : EtaQuot := ⟨[(10, 1), (12, 2), (5, 2), (6, 3)]⟩
def d_833c932f_8a3 : EtaQuot := ⟨[(10, 2), (11, -4), (7, -3), (3, 1)]⟩
def d_a38ca17d_3a6 : EtaQuot := ⟨[(1, 1), (10, 3), (5, 2)]⟩
def d_2b9b8cd8_e32 : EtaQuot := ⟨[(12, 2), (6, 3)]⟩
def d_11f05b95_da0 : EtaQuot := ⟨[(9, -2), (11, -4), (6, 6)]⟩
def d_7f3a9e96_a4d : EtaQuot := ⟨[(8, -1), (9, -4), (10, 4), (11, -2), (12, 1)]⟩
def d_cf8e009e_8a6 : EtaQuot := ⟨[(3, -1), (7, -2), (10, 12), (11, -3), (12, 3)]⟩
def d_e149994c_1b7 : EtaQuot := ⟨[(2, -1), (3, 3), (4, 2), (7, -2), (11, 4), (12, -3), (5, -1)]⟩
def d_ee8bfc53_1e7 : EtaQuot := ⟨[(3, 1), (7, -3), (8, 1), (9, -4)]⟩
def d_4c49578d_c6c : EtaQuot := ⟨[(8, 1), (11, -7), (9, -2)]⟩
def d_cb3ece0c_9c7 : EtaQuot := ⟨[(9, -4), (10, 4), (6, 3), (8, 2)]⟩
def d_d48a43c5_e8f : EtaQuot := ⟨[(4, 1), (7, -4), (10, 4), (11, -12)]⟩
def d_a59d6048_a26 : EtaQuot := ⟨[(4, -1), (7, -4), (8, 4), (10, 4)]⟩
def d_16942259_7af : EtaQuot := ⟨[(1, 1), (8, 5), (10, 4), (12, -1), (4, -2)]⟩
def d_05ead7cc_d1b : EtaQuot := ⟨[(2, -1), (5, -1), (8, 11), (9, -4), (10, 1), (11, 1), (12, 1)]⟩
def d_c1ae1eb3_6da : EtaQuot := ⟨[(8, 4), (9, -2), (10, 1), (11, -2)]⟩
def d_e8070e9d_658 : EtaQuot := ⟨[(9, -8), (10, 7), (5, -1), (6, -1)]⟩
def d_b20a8898_c2d : EtaQuot := ⟨[(1, 1), (4, 1), (6, 4), (8, 4), (10, 12)]⟩
def d_2eb596c1_76b : EtaQuot := ⟨[(8, 3), (11, -4), (10, 2)]⟩
def d_c7c9cbb9_bd2 : EtaQuot := ⟨[(5, 1), (6, -2), (8, 7), (10, 4), (11, -12), (7, -1)]⟩
def d_14389dee_afd : EtaQuot := ⟨[(5, 1), (11, -4)]⟩
def d_c2639eba_aff : EtaQuot := ⟨[(2, 1), (3, 1), (6, -2), (11, 1), (10, 4)]⟩
def d_3c09010d_5fe : EtaQuot := ⟨[(1, 1), (8, 2), (10, 12)]⟩
def d_779789f8_1ba : EtaQuot := ⟨[(8, 4), (11, -4), (4, 2), (5, 1)]⟩
def d_fe629073_18e : EtaQuot := ⟨[(3, 2), (4, 2), (9, -2), (10, 4), (12, 12)]⟩
def d_fcbc5c1d_011 : EtaQuot := ⟨[(7, -2), (8, 2), (10, 2), (11, -12), (9, -1)]⟩
def d_738da1de_d60 : EtaQuot := ⟨[(3, 3), (4, 2), (10, 3), (12, -1)]⟩
def d_be13fe8a_e17 : EtaQuot := ⟨[(4, 2), (6, -2), (7, 1), (8, 3), (9, -4), (10, 2)]⟩
def d_28f2f792_176 : EtaQuot := ⟨[(4, 2), (6, -3), (7, 1), (12, -12), (11, -2)]⟩
def d_dbc36c2d_cea : EtaQuot := ⟨[(3, 2), (7, -4), (11, -1)]⟩
def d_ab56b5b0_529 : EtaQuot := ⟨[(8, 2), (9, -2), (10, 6), (12, -24)]⟩
def d_5b46ecb4_24a : EtaQuot := ⟨[(3, 2), (7, -1), (8, 4), (10, 4), (12, -4)]⟩
def d_28ae0216_3bd : EtaQuot := ⟨[(6, 1), (8, 4), (9, -2), (10, 5)]⟩
def d_ee96fe19_c94 : EtaQuot := ⟨[(9, -1), (11, -3), (7, -1), (10, 2)]⟩
def d_b2ad728c_870 : EtaQuot := ⟨[(3, 2), (12, 1), (6, 1), (11, -2)]⟩
def d_9a300e96_463 : EtaQuot := ⟨[(9, -5), (10, 4), (11, -4)]⟩
def d_604aad88_c56 : EtaQuot := ⟨[(3, -1), (7, 1), (9, -2), (11, -1)]⟩
def d_1c36bf9c_ec9 : EtaQuot := ⟨[(8, 3), (11, -2), (12, 3)]⟩
def d_36a88653_e87 : EtaQuot := ⟨[(8, 1), (12, -4), (4, 1), (6, -2)]⟩
def d_1ffe6879_9f4 : EtaQuot := ⟨[(5, 1), (6, 3), (7, -4), (8, 1), (10, 2)]⟩
def d_d771521c_e18 : EtaQuot := ⟨[(1, 1), (4, 3), (8, 2), (10, 12)]⟩
def d_2bc84042_cc1 : EtaQuot := ⟨[(5, 1), (8, 4), (10, 2), (11, -2), (3, 1)]⟩
def d_ab85b198_0b4 : EtaQuot := ⟨[(9, -4), (10, 4), (11, -2), (6, 1)]⟩
def d_d3f0b5ad_3d9 : EtaQuot := ⟨[(3, 2), (7, -4), (8, 3), (9, -3)]⟩
def d_2955c71a_730 : EtaQuot := ⟨[(3, 3), (7, -1), (11, -12)]⟩
def d_ecea6104_236 : EtaQuot := ⟨[(9, -3), (6, 3)]⟩
def d_6c58978a_68a : EtaQuot := ⟨[(6, 3), (8, 3), (10, 4), (11, -3), (12, -2)]⟩
def d_c47e6d86_01b : EtaQuot := ⟨[(8, 1), (9, -2), (10, 3)]⟩
def d_7422553d_013 : EtaQuot := ⟨[(8, 1), (9, -1)]⟩
def d_ea67ab28_51a : EtaQuot := ⟨[(6, 2), (10, 4), (11, -4)]⟩
def d_2601bfa1_bc9 : EtaQuot := ⟨[(6, 1), (7, -2), (8, 1), (11, -6)]⟩
def d_caaafc30_31c : EtaQuot := ⟨[(5, 1), (11, -4), (4, 1)]⟩
def d_abee56e2_12d : EtaQuot := ⟨[(1, 1), (10, 4), (11, -4)]⟩
def d_f5930387_203 : EtaQuot := ⟨[(2, 1), (7, 4)]⟩
def d_d8a5fcb2_539 : EtaQuot := ⟨[(8, 2), (10, 2), (11, -6)]⟩
def d_601271d0_71f : EtaQuot := ⟨[(11, -12), (10, 3), (3, -1), (4, 1)]⟩
def d_b6ab7de8_583 : EtaQuot := ⟨[(3, 1), (6, -1), (8, 4), (10, 6)]⟩
def d_6dd84ebb_190 : EtaQuot := ⟨[(3, 2), (8, 1), (9, 3), (10, 4), (11, 1), (12, 3)]⟩
def d_eae7d053_afd : EtaQuot := ⟨[(11, -2), (10, 4), (3, 1)]⟩
def d_c13a42b5_0c0 : EtaQuot := ⟨[(2, -1), (4, 4), (8, 3), (12, 1)]⟩
def d_272da95c_451 : EtaQuot := ⟨[(6, 3), (7, -4), (8, 6), (9, -1), (12, 1), (3, 1)]⟩
def d_5878e976_56a : EtaQuot := ⟨[(6, 1), (8, 4), (11, -3), (10, 1)]⟩
def d_3a561d69_2b2 : EtaQuot := ⟨[(9, -8), (10, 4), (8, 4)]⟩
def d_fa611fec_42e : EtaQuot := ⟨[(4, 2), (7, 2), (10, 2), (12, -4)]⟩
def d_2ce3e943_55b : EtaQuot := ⟨[(6, 2), (7, -3), (8, 1), (9, -1), (11, -4)]⟩
def d_2e973906_e57 : EtaQuot := ⟨[(5, 1), (7, -1), (10, 3), (12, 1), (11, -4)]⟩
def d_063b0e2b_e33 : EtaQuot := ⟨[(4, 1), (3, 4)]⟩
def d_d2cccd53_081 : EtaQuot := ⟨[(8, 4), (9, -3), (10, 4), (12, 12), (6, 1)]⟩
def d_4751e9b9_480 : EtaQuot := ⟨[(3, 2), (7, -2), (8, 1)]⟩
def d_a4425044_abd : EtaQuot := ⟨[(7, -4), (10, 7), (11, -4), (12, 4)]⟩
def d_1886928a_7a4 : EtaQuot := ⟨[(3, 1), (5, 2), (6, 3), (7, -4)]⟩
def d_f2fedf07_612 : EtaQuot := ⟨[(10, 4), (11, -3), (3, 2)]⟩
def d_6c93a193_819 : EtaQuot := ⟨[(9, -3), (6, 2), (7, -4)]⟩
def d_a1967706_dd4 : EtaQuot := ⟨[(4, 2), (7, 1), (10, 2), (11, -2), (12, -4)]⟩
def d_d7c1e97d_151 : EtaQuot := ⟨[(4, 1), (8, 1), (9, -3), (11, -12), (12, 2)]⟩
def d_7a0e691a_939 : EtaQuot := ⟨[(9, -2), (10, 12), (5, -1), (7, -2)]⟩
def d_38b99c9e_c70 : EtaQuot := ⟨[(10, 12), (11, -2), (5, -2)]⟩
def d_41174f6b_920 : EtaQuot := ⟨[(1, 1), (2, -1), (4, 3), (9, -3), (10, 3), (11, -3)]⟩
def d_7f966706_aa4 : EtaQuot := ⟨[(6, 1), (8, 1), (9, -3), (11, -12)]⟩
def d_8a0c5f22_16b : EtaQuot := ⟨[(5, 2), (6, 4), (9, -4), (10, 3), (12, 1)]⟩
def d_60519e84_a97 : EtaQuot := ⟨[(3, -2), (6, 4), (7, 2), (8, -3), (12, 2)]⟩
def d_71f281c0_292 : EtaQuot := ⟨[(1, 1), (5, -1), (8, -2), (9, -6), (11, -12)]⟩
def d_cc9a05a2_3da : EtaQuot := ⟨[(7, -3), (8, 3), (9, -2), (11, -2), (12, -2)]⟩
def d_a88b88a9_739 : EtaQuot := ⟨[(1, 2), (10, 1), (5, 1)]⟩
def d_e46131e3_8c2 : EtaQuot := ⟨[(3, 3), (7, -2), (8, 2), (11, -4)]⟩
def d_470e118c_90c : EtaQuot := ⟨[(3, 2), (6, 2), (11, -10)]⟩
def d_ec44fec6_592 : EtaQuot := ⟨[(1, 1), (10, 3)]⟩
def d_07da9cc9_3d2 : EtaQuot := ⟨[(8, 4), (11, -2)]⟩
def d_d7337903_647 : EtaQuot := ⟨[(6, 2), (9, -3), (10, 3), (12, -1), (11, -2)]⟩
def d_e4a17dc7_ef5 : EtaQuot := ⟨[(3, 2), (4, 2), (10, 4), (8, 2)]⟩
def d_311bccdc_edd : EtaQuot := ⟨[(4, -1), (6, 4), (9, -3), (11, -9), (12, -12)]⟩
def d_d3c24842_896 : EtaQuot := ⟨[(1, 1), (8, 1), (9, -3), (11, -12)]⟩
def d_51744401_31b : EtaQuot := ⟨[(3, 3), (8, 3), (10, 9), (11, 1)]⟩
def d_a70892f3_23a : EtaQuot := ⟨[(3, 1), (6, 1), (11, -4), (12, -24), (7, -2)]⟩
def d_66e6bdcf_3dc : EtaQuot := ⟨[(10, 2), (6, 3), (9, -4)]⟩
def d_561aa659_c58 : EtaQuot := ⟨[(3, -1), (4, 2), (8, 1), (11, -12), (12, 4)]⟩
def d_aca03496_813 : EtaQuot := ⟨[(6, 4), (9, -1), (11, -4)]⟩
def d_2edceaf6_109 : EtaQuot := ⟨[(8, 2), (10, 4), (11, -12)]⟩
def d_824ea4ae_af0 : EtaQuot := ⟨[(3, 2), (6, 2), (9, 1), (10, 2)]⟩
def d_08876410_b11 : EtaQuot := ⟨[(3, 1), (6, 2), (8, 3), (10, 1)]⟩
def d_82ff6f5f_44d : EtaQuot := ⟨[(10, 12), (4, 2), (12, 1), (6, 3)]⟩
def d_413e94dc_e99 : EtaQuot := ⟨[(9, -1), (10, 2), (11, -4), (12, 4)]⟩
def d_17013e1a_6b7 : EtaQuot := ⟨[(6, 2), (7, -1), (9, 1), (12, -3), (11, -1)]⟩
def d_8da8c6c6_b8c : EtaQuot := ⟨[(8, 2), (3, 3), (12, -10), (7, -1)]⟩
def d_43fb5449_ba0 : EtaQuot := ⟨[(3, 1), (7, -2), (11, -2), (12, 3)]⟩
def d_eac562fc_8c4 : EtaQuot := ⟨[(4, -1), (7, -4), (8, 3), (10, 2), (11, -3)]⟩
def d_6145cd1f_816 : EtaQuot := ⟨[(5, 1), (6, 2), (8, 2), (9, -2), (10, 1), (11, -2)]⟩
def d_28f71c29_340 : EtaQuot := ⟨[(1, 2), (8, 2), (10, 4), (11, -4)]⟩
def d_39f230d8_eaf : EtaQuot := ⟨[(9, -2), (12, -3), (11, -4)]⟩
def d_6490b4dd_357 : EtaQuot := ⟨[(3, -1)]⟩
def d_2a93761e_90d : EtaQuot := ⟨[(8, 6), (11, -4), (10, 4)]⟩
def d_4d45a487_730 : EtaQuot := ⟨[(6, 4), (5, 2)]⟩
def d_02a8923e_d49 : EtaQuot := ⟨[(12, -1), (7, -3), (8, 4)]⟩
def d_5ea9ca0e_7c4 : EtaQuot := ⟨[(3, 2), (9, 1), (10, 3), (4, 1)]⟩
def d_c335384b_dc7 : EtaQuot := ⟨[(3, 3), (6, -1), (8, 1), (10, 4)]⟩
def d_c4416eea_8e7 : EtaQuot := ⟨[(6, 4), (8, 3), (10, 4), (11, -1), (12, -2)]⟩
def d_9521f93b_949 : EtaQuot := ⟨[(4, 2), (7, 1), (8, -1), (10, 4)]⟩
def d_b19853f3_4ec : EtaQuot := ⟨[(4, 2), (5, 1), (6, 4), (10, 12), (12, -4)]⟩
def d_0089752e_f99 : EtaQuot := ⟨[(8, 2), (11, -4), (12, 2), (7, -1)]⟩
def d_5d852da1_55b : EtaQuot := ⟨[(1, 1), (9, -1), (10, 3), (11, -3)]⟩
def d_eeda8805_7d3 : EtaQuot := ⟨[(3, 2), (8, 4), (10, 2), (11, -4), (9, -2)]⟩
def d_fb2d3c32_387 : EtaQuot := ⟨[(3, 4), (8, 2), (10, 3)]⟩
def d_661e7895_fb6 : EtaQuot := ⟨[(1, 2), (5, 1), (9, -4), (11, -2)]⟩
def d_229db8e1_11a : EtaQuot := ⟨[(9, -4), (10, 12), (7, -2), (5, -1)]⟩
def d_46b02978_21b : EtaQuot := ⟨[(5, 3), (6, 1), (7, -4), (8, 2), (10, 3)]⟩
def d_13824e0f_1ea : EtaQuot := ⟨[(9, -2), (10, 3), (11, -4)]⟩
def d_a554f332_76d : EtaQuot := ⟨[(8, 4), (3, 2), (6, 2)]⟩
def d_72eeb26a_2f9 : EtaQuot := ⟨[(3, 3), (8, 3)]⟩
def d_64d1b9ee_e7a : EtaQuot := ⟨[(3, 3), (11, -2), (7, -2)]⟩
def d_3c518b08_112 : EtaQuot := ⟨[(3, 2), (6, 2), (7, -2)]⟩
def d_ada2fb6c_85a : EtaQuot := ⟨[(11, -1), (12, 2), (9, -4)]⟩
def d_909063f4_fe7 : EtaQuot := ⟨[(3, 1), (5, 1), (6, 4), (11, -1)]⟩
def d_1f29ec52_000 : EtaQuot := ⟨[(3, 1), (7, -3), (9, -4), (10, 4), (11, -6)]⟩
def d_620fc046_5cf : EtaQuot := ⟨[(9, -3), (10, 5), (11, -12), (12, 12), (6, 1)]⟩
def d_456b051b_f33 : EtaQuot := ⟨[(9, -4), (11, -4)]⟩
def d_6e2db9e4_3fa : EtaQuot := ⟨[(9, -1), (7, -4), (11, -2)]⟩
def d_161f8826_940 : EtaQuot := ⟨[(3, -1), (10, 4), (11, -2), (12, 3), (1, 2)]⟩
def d_b9d41f53_3b5 : EtaQuot := ⟨[(11, -3), (3, 3), (4, 1)]⟩
def d_912fe5f9_2c2 : EtaQuot := ⟨[(4, 3), (7, 1), (12, -4), (9, -2)]⟩
def d_66b7e6cc_195 : EtaQuot := ⟨[(12, 4), (6, 2), (10, 2)]⟩
def d_12557535_95c : EtaQuot := ⟨[(6, 1), (7, -2), (9, -4), (11, -2), (12, 1)]⟩
def d_13435407_002 : EtaQuot := ⟨[(9, -4), (10, 4), (11, -12)]⟩
def d_59d88825_0b2 : EtaQuot := ⟨[(3, 2), (6, 1), (8, 1), (10, 4)]⟩
def d_2b9b443e_f3c : EtaQuot := ⟨[(3, 1), (6, 3), (7, -4), (8, 4), (9, -2)]⟩
def d_bfc2b819_be9 : EtaQuot := ⟨[(9, -2), (12, -2), (11, -4)]⟩
def d_662c4b2f_74b : EtaQuot := ⟨[(8, 2), (11, -4), (6, 1), (7, -4)]⟩
def d_c8f66120_04f : EtaQuot := ⟨[(4, -1), (7, -3), (8, 1), (10, 4), (11, -1)]⟩
def d_88421914_08e : EtaQuot := ⟨[(8, 2), (11, -2)]⟩
def d_3b1db22c_8ac : EtaQuot := ⟨[(3, 2), (9, 2), (11, -4), (12, -2), (6, 2)]⟩
def d_ba56a556_a09 : EtaQuot := ⟨[(5, 2), (6, 2), (7, -2), (10, 4)]⟩
def d_e82c2d15_ce3 : EtaQuot := ⟨[(3, 1), (4, 2), (6, 1), (7, -1), (8, 2), (9, -4), (11, -2), (2, -1)]⟩
def d_f63060d9_b82 : EtaQuot := ⟨[(11, -12), (5, 1), (7, -2)]⟩
def d_61038119_811 : EtaQuot := ⟨[(4, 1), (7, 2), (10, 3), (11, -4), (12, 3)]⟩
def d_fdd37ac1_282 : EtaQuot := ⟨[(3, 2), (6, 2), (10, 3), (11, -4)]⟩
def d_43058a72_2ae : EtaQuot := ⟨[(7, -3), (8, 4), (9, -2), (11, -4), (6, 1)]⟩
def d_daaf1428_ca6 : EtaQuot := ⟨[(1, 1), (5, 1), (10, 1)]⟩
def d_2fdf8d88_4d8 : EtaQuot := ⟨[(4, 1), (6, -2), (7, 3), (8, 4), (9, -4)]⟩
def d_9c868dc7_41c : EtaQuot := ⟨[(10, 2), (12, -1), (9, -2)]⟩
def d_87d5639a_8c4 : EtaQuot := ⟨[(11, -2), (12, 4), (10, 4)]⟩
def d_139e195b_e7a : EtaQuot := ⟨[(8, 4), (9, -2), (10, 2), (11, -9), (12, -1)]⟩
def d_5434cced_159 : EtaQuot := ⟨[(4, 1), (11, -3), (12, -4), (3, 4)]⟩
def d_d7abcb83_b93 : EtaQuot := ⟨[(3, 2), (6, 2), (9, 2), (10, 4), (11, -4), (7, -1)]⟩
def d_5ef662a5_e1f : EtaQuot := ⟨[(1, 1), (7, -3), (9, -2), (10, 1), (11, -4)]⟩
def d_de77ba86_ed2 : EtaQuot := ⟨[(5, 1), (6, 3), (8, 2), (9, -1), (10, 1), (12, 1)]⟩
def d_b5590ab9_907 : EtaQuot := ⟨[(3, 1), (7, -3), (9, -5), (10, 1), (11, -4)]⟩
def d_7e6d05f5_f4c : EtaQuot := ⟨[(12, -1), (6, 1), (7, -4), (3, 2)]⟩
def d_bafda187_98d : EtaQuot := ⟨[(2, 1), (11, -4), (10, 4)]⟩
def d_a0e67c52_919 : EtaQuot := ⟨[(6, 2), (9, -5), (11, -10), (12, -2)]⟩
def d_d46437dc_2c6 : EtaQuot := ⟨[(4, 1), (6, 3), (7, -2), (8, -2), (10, 12), (11, -12), (12, -3)]⟩
def d_320538f1_b66 : EtaQuot := ⟨[(8, 2), (9, -2), (11, -3)]⟩
def d_a64705d8_fce : EtaQuot := ⟨[(10, 1), (11, -11), (9, -4)]⟩
def d_55899e83_02e : EtaQuot := ⟨[(9, -1), (10, 4), (11, -4), (12, 12)]⟩
def d_fd47e986_9f1 : EtaQuot := ⟨[(6, 1), (7, -4), (11, -8), (12, 3)]⟩
def d_d5cbb0c7_090 : EtaQuot := ⟨[(4, 1), (5, 2), (11, -4)]⟩
def d_102ce4c0_51b : EtaQuot := ⟨[(8, 4), (9, -2), (10, 4), (6, 1)]⟩
def d_9f9def2a_8fb : EtaQuot := ⟨[(6, 2), (7, 1), (8, 1), (10, 2), (12, -4), (11, -2)]⟩
def d_df298c64_1d2 : EtaQuot := ⟨[(9, -2), (11, -7)]⟩
def d_efa56368_c60 : EtaQuot := ⟨[(5, 1), (6, 4), (7, -4), (9, -1), (11, -1), (12, -3)]⟩
def d_6e92b84b_8d3 : EtaQuot := ⟨[(5, -1), (10, 12), (11, -4), (8, 2)]⟩
def d_0dc2f13a_1a6 : EtaQuot := ⟨[(1, 1), (10, 6)]⟩
def d_aa2a8533_451 : EtaQuot := ⟨[(8, 3), (10, 3), (11, -3)]⟩
def d_0579e7a2_311 : EtaQuot := ⟨[(3, 3), (4, 1), (10, 3), (12, -24)]⟩
def d_6369b179_eb0 : EtaQuot := ⟨[(6, 4), (7, -1), (8, 2), (10, 3), (12, 12), (9, -4)]⟩
def d_3a22fb2b_863 : EtaQuot := ⟨[(7, -1), (10, 4)]⟩
def d_84329a4c_630 : EtaQuot := ⟨[(8, 1), (6, 3)]⟩
def d_45f56532_2d1 : EtaQuot := ⟨[(6, -1), (9, -3), (10, 4), (11, -3)]⟩
def d_661dda4e_dfa : EtaQuot := ⟨[(3, 4), (5, -2), (7, -3), (9, 2), (11, -3), (12, 2)]⟩
def d_b06b7088_a9c : EtaQuot := ⟨[(3, 3), (5, -2), (7, -4), (9, 1), (10, -4), (12, 3), (8, 1)]⟩
def d_8e05de4e_df6 : EtaQuot := ⟨[(8, 2), (11, -12), (6, 4)]⟩
def d_ce7690ac_716 : EtaQuot := ⟨[(4, 1), (5, 2), (8, 1), (9, -3)]⟩
def d_2f6d69d0_8fc : EtaQuot := ⟨[(7, -4), (10, 1)]⟩
def d_e459677e_0cb : EtaQuot := ⟨[(8, 3), (9, -4), (10, 1), (11, -1)]⟩
def d_57ec982a_b5f : EtaQuot := ⟨[(5, 2), (6, 2), (7, -4), (11, -1), (12, 4)]⟩
def d_eaa67496_39e : EtaQuot := ⟨[(10, 8), (11, -4), (12, -1), (4, 2), (3, 2)]⟩
def d_9b22946b_329 : EtaQuot := ⟨[(8, 2), (9, -4), (3, 2)]⟩
def d_6ff86b44_519 : EtaQuot := ⟨[(9, -4), (11, -4), (10, 1)]⟩
def d_3823f639_815 : EtaQuot := ⟨[(4, 4), (7, 1), (9, -4), (12, 3), (6, -1)]⟩
def d_7212797d_9b0 : EtaQuot := ⟨[(8, -1), (9, -1), (12, -2), (4, 2)]⟩
def d_91f5e024_7b5 : EtaQuot := ⟨[(10, 3), (11, -12)]⟩
def d_b75d5f80_19a : EtaQuot := ⟨[(6, 4), (8, 4), (9, -3), (11, -3)]⟩
def d_450c24b7_f65 : EtaQuot := ⟨[(8, 2), (3, 1), (12, -1)]⟩
def d_c1222c51_bef : EtaQuot := ⟨[(7, -3), (8, 2), (9, -2), (10, 8), (12, 24)]⟩
def d_f211bda0_a30 : EtaQuot := ⟨[(10, 1), (12, 1), (6, 3)]⟩
def d_16f87864_787 : EtaQuot := ⟨[(3, 1), (4, 1), (8, 1), (12, 4)]⟩
def d_7306a38a_8fa : EtaQuot := ⟨[(3, 3), (10, 2), (11, -3), (4, 2)]⟩
def d_b5c26eb3_87d : EtaQuot := ⟨[(4, 4), (8, 3), (9, -3), (10, 3), (7, 2)]⟩
def d_d26a1079_3ec : EtaQuot := ⟨[(9, -4), (11, -5), (5, 1), (7, -2)]⟩
def d_15411126_1f7 : EtaQuot := ⟨[(4, 3), (8, 3), (9, -4), (11, -4), (12, 24)]⟩
def d_e6df2ec0_556 : EtaQuot := ⟨[(5, 1), (6, 3), (7, -4), (9, -3)]⟩
def d_b4b761a9_9b0 : EtaQuot := ⟨[(1, 1), (11, -2), (12, 12), (10, 2)]⟩
def d_46a71c1f_819 : EtaQuot := ⟨[(9, -3), (11, -3), (6, 2), (4, -1)]⟩
def d_d4057cbb_174 : EtaQuot := ⟨[(8, 3), (3, 3), (7, -3)]⟩
def d_b72a4744_25a : EtaQuot := ⟨[(6, 2), (9, -2), (11, -2), (5, 2)]⟩
def d_f7efa926_2a0 : EtaQuot := ⟨[(12, -3), (7, -2), (11, -4)]⟩
def d_9fd8c9dc_028 : EtaQuot := ⟨[(3, 1), (6, 3), (8, 2), (10, 5), (11, -2), (12, 12)]⟩
def d_ee41b7a3_505 : EtaQuot := ⟨[(11, -4), (12, -24), (6, 4)]⟩
def d_7934a48e_baf : EtaQuot := ⟨[(5, 1), (6, 1), (8, 1), (10, 4), (12, 3), (3, 2)]⟩
def d_6699a6f5_e72 : EtaQuot := ⟨[(8, 2), (10, 2), (5, 1), (6, 4)]⟩
def d_bfc3c544_b6d : EtaQuot := ⟨[(3, 1), (7, 1), (8, 4), (9, -3), (10, 6)]⟩
def d_7e9d2075_386 : EtaQuot := ⟨[(8, 2), (10, 4), (3, 1), (12, -1)]⟩
def d_a2db330e_b7b : EtaQuot := ⟨[(3, 2), (4, 1), (11, -2), (12, 24)]⟩
def d_82fb4068_d98 : EtaQuot := ⟨[(9, -2)]⟩
def d_27d333b1_6c6 : EtaQuot := ⟨[(3, 3), (4, 1), (9, -2), (11, -2)]⟩
def d_cc48ac4a_702 : EtaQuot := ⟨[(2, -1), (4, 3), (6, 3), (9, -2), (10, 7)]⟩
def d_5bd40803_465 : EtaQuot := ⟨[(9, -4), (10, 4), (11, -3), (12, 1)]⟩
def d_29e22213_e03 : EtaQuot := ⟨[(3, 1), (5, 1), (6, 2), (7, -3), (11, -2)]⟩
def d_56711609_246 : EtaQuot := ⟨[(9, -4), (10, 1)]⟩
def d_5e8a0090_3e5 : EtaQuot := ⟨[(3, 1), (6, 5), (8, 4), (11, -1)]⟩
def d_0b9aaa4a_a8b : EtaQuot := ⟨[(9, -3), (12, 2), (11, -2)]⟩
def d_5495f618_e36 : EtaQuot := ⟨[(3, 1), (5, 2), (6, 2), (7, -1), (11, -2)]⟩
def d_59f6c1d6_a94 : EtaQuot := ⟨[(9, -1), (10, 2), (12, -2), (1, 2)]⟩
def d_5a566fe4_ef3 : EtaQuot := ⟨[(2, -3), (4, 8), (7, -3), (8, 2), (11, -2), (12, -24)]⟩
def d_206a1b06_b4d : EtaQuot := ⟨[(4, 4), (8, 3), (9, -2), (10, 1), (12, 4)]⟩
def d_0af33475_a33 : EtaQuot := ⟨[(5, 1), (6, 4), (10, 2), (12, 3)]⟩
def d_f390afbc_847 : EtaQuot := ⟨[(1, 1), (8, 3), (10, 2), (3, 1)]⟩
def d_866d2bb5_e30 : EtaQuot := ⟨[(3, 3), (8, 3), (10, 1), (11, -2), (12, -1)]⟩
def d_41d1f591_512 : EtaQuot := ⟨[(11, -12), (12, 24), (10, 4)]⟩
def d_c083f2c8_1bb : EtaQuot := ⟨[(11, -8), (4, 2), (6, -1)]⟩
def d_2dbd8806_542 : EtaQuot := ⟨[(8, 4), (9, -1), (10, 4), (11, -1), (12, 12)]⟩
def d_283788b4_8e0 : EtaQuot := ⟨[(8, 2), (3, 2), (12, 4)]⟩
def d_6783c136_2f4 : EtaQuot := ⟨[(3, 2), (11, -1), (12, -5)]⟩
def d_e3cfd8fd_ae0 : EtaQuot := ⟨[(3, 2), (5, 2), (6, 1), (8, 2), (12, 3)]⟩
def d_570affc7_02c : EtaQuot := ⟨[(5, 2), (6, 2)]⟩
def d_f61af7e5_4f5 : EtaQuot := ⟨[(8, 4), (9, -4), (10, 3)]⟩
def d_4a633f3e_787 : EtaQuot := ⟨[(8, 2), (3, 3), (7, -1)]⟩
def d_636dfc8e_378 : EtaQuot := ⟨[(11, -3), (4, 1), (10, 4)]⟩
def d_04c1e69a_cbe : EtaQuot := ⟨[(7, -1), (8, 1), (9, -5), (10, 4), (11, -4)]⟩
def d_293e100c_362 : EtaQuot := ⟨[(9, -4), (10, 2), (11, -12)]⟩
def d_4b19a6ec_918 : EtaQuot := ⟨[(1, 1), (10, 4)]⟩
def d_59d084fa_ad9 : EtaQuot := ⟨[(6, 1), (7, -4), (8, 3), (10, 2)]⟩
def d_961951d6_f35 : EtaQuot := ⟨[(9, -1), (10, 4), (11, -2)]⟩
def d_0025c44d_ac5 : EtaQuot := ⟨[(8, 3), (4, 2), (9, -1)]⟩
def d_f9111d55_e52 : EtaQuot := ⟨[(6, 4), (7, -4), (9, -2), (10, 2)]⟩
def d_20d71b90_4ba : EtaQuot := ⟨[(6, 1), (8, 4), (9, -3), (11, -1), (12, 3)]⟩
def d_c2df5b64_aa6 : EtaQuot := ⟨[(11, -4), (10, 4)]⟩
def d_7ca413c5_560 : EtaQuot := ⟨[(10, 12), (11, -3), (5, -3)]⟩
def d_21341671_b41 : EtaQuot := ⟨[(6, 2), (7, -2), (9, -5), (12, -12), (11, -4)]⟩
def d_5e2d860f_a5f : EtaQuot := ⟨[(8, 4), (9, -5), (11, -1), (12, 7)]⟩
def d_1b232ece_9f1 : EtaQuot := ⟨[(10, 4), (11, -10), (8, 1)]⟩
def d_1aef7cbe_27a : EtaQuot := ⟨[(9, -3), (11, -4), (12, 2), (1, 1)]⟩
def d_cb167a96_93d : EtaQuot := ⟨[(1, 1), (6, -1), (9, -3), (10, 2), (11, -4)]⟩
def d_79ec115a_805 : EtaQuot := ⟨[(10, 4), (5, 2), (6, 3)]⟩
def d_6a483814_146 : EtaQuot := ⟨[(1, 1), (9, -2), (10, 4), (11, -3), (12, -4)]⟩
def d_64fce78d_7ac : EtaQuot := ⟨[(10, 3), (11, -12), (7, -1)]⟩
def d_b1c4e167_0ee : EtaQuot := ⟨[(11, -4), (6, 2)]⟩
def d_46b132b4_aea : EtaQuot := ⟨[(5, -2), (6, -1), (8, 3), (10, 12), (11, -2)]⟩
def d_a772e066_7bf : EtaQuot := ⟨[(4, -1), (6, 2), (7, -3), (9, -8), (10, 3), (12, -2)]⟩

def checkBatch : List Bool := [
  (modularWeight d_e46d9956_a9e == 1/2),
  (modularWeight d_d08c97f0_c08 == 1/2),
  (modularWeight d_116e8203_b81 == 1/2),
  (modularWeight d_5312c21c_e52 == 1/2),
  (modularWeight d_8317b09b_72e == 1/2),
  (modularWeight d_eb03f21e_c0a == 1/2),
  (modularWeight d_e10679e2_442 == 1/2),
  (modularWeight d_f0d9021e_053 == 1/2),
  (modularWeight d_a626695f_1b1 == 1/2),
  (modularWeight d_ade3259b_76b == 1/2),
  (modularWeight d_900bb087_3e5 == 1/2),
  (modularWeight d_579d5934_bc6 == 1/2),
  (modularWeight d_c222ac5c_515 == 1/2),
  (modularWeight d_5c01cd04_5f8 == 1/2),
  (modularWeight d_2222e5b4_b6d == 1/2),
  (modularWeight d_522b77ed_d01 == 1/2),
  (modularWeight d_6c45da89_243 == 1/2),
  (modularWeight d_77ead353_8d8 == 1/2),
  (modularWeight d_2c70cfff_714 == 1/2),
  (modularWeight d_930fe7cb_01c == 1/2),
  (modularWeight d_807208fe_d33 == 1/2),
  (modularWeight d_42763ef0_03b == 1/2),
  (modularWeight d_89968a81_e4c == 1/2),
  (modularWeight d_88746e42_d74 == 1/2),
  (modularWeight d_50a39513_894 == 1/2),
  (modularWeight d_39c56088_623 == 1/2),
  (modularWeight d_bbb9ebf8_2f1 == 1/2),
  (modularWeight d_e87a636f_27a == 1/2),
  (modularWeight d_56f1cf6b_bfd == 1/2),
  (modularWeight d_750e49ec_8cf == 1/2),
  (modularWeight d_69ad9c99_0ec == 1/2),
  (modularWeight d_7859bd56_029 == 1/2),
  (modularWeight d_b4a25fbe_b90 == 1/2),
  (modularWeight d_e56fdf39_8e3 == 1/2),
  (modularWeight d_5ea9e681_cd7 == 1/2),
  (modularWeight d_30466116_cce == 1/2),
  (modularWeight d_e64fad96_dbd == 1/2),
  (modularWeight d_38bd5146_d75 == 1/2),
  (modularWeight d_1ec02312_96d == 1/2),
  (modularWeight d_f2841284_167 == 1/2),
  (modularWeight d_801f5539_45c == 1/2),
  (modularWeight d_745150f7_f49 == 1/2),
  (modularWeight d_f59ff17a_3f9 == 1/2),
  (modularWeight d_50156515_4e0 == 1/2),
  (modularWeight d_41b228df_f54 == 1/2),
  (modularWeight d_f963b410_c6d == 1/2),
  (modularWeight d_b8d896c2_e08 == 1/2),
  (modularWeight d_ddcbfe4d_c08 == 1/2),
  (modularWeight d_fe5e3852_880 == 1/2),
  (modularWeight d_ec2c7e82_933 == 1/2),
  (modularWeight d_fe943483_5cb == 1/2),
  (modularWeight d_f2ec2a4c_70e == 1/2),
  (modularWeight d_812699f3_648 == 1/2),
  (modularWeight d_12fc5cc3_898 == 1/2),
  (modularWeight d_f85e401e_a54 == 1/2),
  (modularWeight d_efeb392e_85d == 1/2),
  (modularWeight d_a9dd1cb0_200 == 1/2),
  (modularWeight d_ae4ef401_c35 == 1/2),
  (modularWeight d_08f66605_55a == 1/2),
  (modularWeight d_6ad95fd7_f1a == 1/2),
  (modularWeight d_66eaa844_98c == 1/2),
  (modularWeight d_bed15f16_486 == 1/2),
  (modularWeight d_f08a40c0_512 == 1/2),
  (modularWeight d_ce501bca_5ca == 1/2),
  (modularWeight d_bd190d53_83d == 1/2),
  (modularWeight d_cece679e_ac4 == 1/2),
  (modularWeight d_56e6734f_20e == 1/2),
  (modularWeight d_aacf173f_0bb == 1/2),
  (modularWeight d_dbde6529_bbe == 1/2),
  (modularWeight d_6b01415e_129 == 1/2),
  (modularWeight d_cec364ba_2c0 == 1/2),
  (modularWeight d_2120dc71_a26 == 1/2),
  (modularWeight d_018e5fb8_cd2 == 1/2),
  (modularWeight d_7e5b2734_36a == 1/2),
  (modularWeight d_ac4e5a72_b2a == 1/2),
  (modularWeight d_6477185c_a81 == 1/2),
  (modularWeight d_a3870b15_f0f == 1/2),
  (modularWeight d_fd18f387_1aa == 1/2),
  (modularWeight d_4305c607_22f == 1/2),
  (modularWeight d_75f7007a_c3c == 1/2),
  (modularWeight d_67522507_22c == 1/2),
  (modularWeight d_efdfea04_6e7 == 1/2),
  (modularWeight d_2465e716_53b == 1/2),
  (modularWeight d_0d571bf0_87e == 1/2),
  (modularWeight d_a000b0b3_978 == 1/2),
  (modularWeight d_df9101f7_1d7 == 1/2),
  (modularWeight d_3f4c1c45_a3f == 1/2),
  (modularWeight d_5b559f6e_2de == 1/2),
  (modularWeight d_511acd39_b3f == 1/2),
  (modularWeight d_225b3519_de0 == 1/2),
  (modularWeight d_10ae0f97_027 == 1/2),
  (modularWeight d_e1137acf_1f4 == 1/2),
  (modularWeight d_9ac48c46_e40 == 1/2),
  (modularWeight d_a957382c_6a7 == 1/2),
  (modularWeight d_3b2e12e5_827 == 1/2),
  (modularWeight d_58d68cc8_e04 == 1/2),
  (modularWeight d_fdd56268_fdd == 1/2),
  (modularWeight d_8eada35c_967 == 1/2),
  (modularWeight d_b196d58b_db6 == 1/2),
  (modularWeight d_18335d39_495 == 1/2),
  (modularWeight d_897c7e44_491 == 1/2),
  (modularWeight d_362f8f36_239 == 1/2),
  (modularWeight d_33e70480_9f1 == 1/2),
  (modularWeight d_c214435f_712 == 1/2),
  (modularWeight d_093ff446_116 == 1/2),
  (modularWeight d_c066b0fd_33b == 1/2),
  (modularWeight d_5e7bd84d_8e1 == 1/2),
  (modularWeight d_4caaffa8_2cc == 1/2),
  (modularWeight d_c1271795_0f1 == 1/2),
  (modularWeight d_ad3c0af3_aa8 == 1/2),
  (modularWeight d_b650b655_b20 == 1/2),
  (modularWeight d_b716e171_1b1 == 1/2),
  (modularWeight d_e1721e19_b24 == 1/2),
  (modularWeight d_17e2046a_d97 == 1/2),
  (modularWeight d_5d25b144_c8b == 1/2),
  (modularWeight d_a40d2329_b35 == 1/2),
  (modularWeight d_20809c7a_ebe == 1/2),
  (modularWeight d_2373a720_678 == 1/2),
  (modularWeight d_6a04df73_39b == 1/2),
  (modularWeight d_2b7437f4_cb0 == 1/2),
  (modularWeight d_c918769f_df4 == 1/2),
  (modularWeight d_be14b34f_3ed == 1/2),
  (modularWeight d_9aa3298c_873 == 1/2),
  (modularWeight d_77797445_058 == 1/2),
  (modularWeight d_bbec07e9_478 == 1/2),
  (modularWeight d_03afe907_92d == 1/2),
  (modularWeight d_ab778e8d_fe0 == 1/2),
  (modularWeight d_3cf846a2_ecb == 1/2),
  (modularWeight d_44160a41_442 == 1/2),
  (modularWeight d_0fe846a0_6ca == 1/2),
  (modularWeight d_3fd8258b_3f7 == 1/2),
  (modularWeight d_051c1a80_af4 == 1/2),
  (modularWeight d_86315bef_f2d == 1/2),
  (modularWeight d_1096b813_205 == 1/2),
  (modularWeight d_074d5adf_6a1 == 1/2),
  (modularWeight d_c13073d7_887 == 1/2),
  (modularWeight d_73009d11_5c1 == 1/2),
  (modularWeight d_2083fa6e_5e5 == 1/2),
  (modularWeight d_8247d35d_0aa == 1/2),
  (modularWeight d_8c7b2fcc_d2b == 1/2),
  (modularWeight d_0fad0338_34f == 1/2),
  (modularWeight d_589d7cd8_6f0 == 1/2),
  (modularWeight d_d742407c_a77 == 1/2),
  (modularWeight d_e41e7b9a_3ff == 1/2),
  (modularWeight d_fd708092_b5a == 1/2),
  (modularWeight d_df009970_ff7 == 1/2),
  (modularWeight d_32951d33_edc == 1/2),
  (modularWeight d_3c604c7c_4e7 == 1/2),
  (modularWeight d_14015f45_de8 == 1/2),
  (modularWeight d_64c52d82_f40 == 1/2),
  (modularWeight d_d701af84_874 == 1/2),
  (modularWeight d_f3243490_113 == 1/2),
  (modularWeight d_722de966_57a == 1/2),
  (modularWeight d_70ceee0c_b6d == 1/2),
  (modularWeight d_df27c3a6_9e2 == 1/2),
  (modularWeight d_40c1e7b1_72d == 1/2),
  (modularWeight d_bd173cf3_fc6 == 1/2),
  (modularWeight d_3a95b16b_a0c == 1/2),
  (modularWeight d_37f321ff_efe == 1/2),
  (modularWeight d_a50e763b_330 == 1/2),
  (modularWeight d_924813bb_4e4 == 1/2),
  (modularWeight d_6da4ef51_ea9 == 1/2),
  (modularWeight d_d50fe234_206 == 1/2),
  (modularWeight d_95400537_156 == 1/2),
  (modularWeight d_793a01a8_709 == 1/2),
  (modularWeight d_f3f4f87c_bc9 == 1/2),
  (modularWeight d_f4ed7e6d_788 == 1/2),
  (modularWeight d_b7e44971_ca3 == 1/2),
  (modularWeight d_a8bd9932_2dc == 1/2),
  (modularWeight d_77b5cb53_8bb == 1/2),
  (modularWeight d_095dea1c_5e6 == 1/2),
  (modularWeight d_780b190f_6b1 == 1/2),
  (modularWeight d_91130e03_a15 == 1/2),
  (modularWeight d_ce2c3ecb_890 == 1/2),
  (modularWeight d_31e08508_592 == 1/2),
  (modularWeight d_5a9fdf90_464 == 1/2),
  (modularWeight d_b9b92dc8_af1 == 1/2),
  (modularWeight d_1391e369_4c2 == 1/2),
  (modularWeight d_e1fb1c00_6ef == 1/2),
  (modularWeight d_b2b3c861_bac == 1/2),
  (modularWeight d_81f07814_708 == 1/2),
  (modularWeight d_f77df2fb_53a == 1/2),
  (modularWeight d_db864376_5cf == 1/2),
  (modularWeight d_59544080_71b == 1/2),
  (modularWeight d_60305155_31f == 1/2),
  (modularWeight d_85bb1fb0_f79 == 1/2),
  (modularWeight d_8133c06a_c45 == 1/2),
  (modularWeight d_bfb39e30_fdd == 1/2),
  (modularWeight d_4db0fa68_696 == 1/2),
  (modularWeight d_29a5b3f7_42e == 1/2),
  (modularWeight d_adc70aed_54d == 1/2),
  (modularWeight d_bf3ae8b2_757 == 1/2),
  (modularWeight d_c976750b_d61 == 1/2),
  (modularWeight d_2fc91a15_dcf == 1/2),
  (modularWeight d_6bbd4610_2a8 == 1/2),
  (modularWeight d_e5dbbecc_765 == 1/2),
  (modularWeight d_bf9a9dca_0d9 == 1/2),
  (modularWeight d_dd560ed8_386 == 1/2),
  (modularWeight d_e226ac03_e0e == 1/2),
  (modularWeight d_119ff014_ca3 == 1/2),
  (modularWeight d_59682fd3_b4b == 1/2),
  (modularWeight d_a008ab76_722 == 1/2),
  (modularWeight d_d17a0c31_b88 == 1/2),
  (modularWeight d_1ee0292f_39d == 1/2),
  (modularWeight d_2b854b05_68a == 1/2),
  (modularWeight d_21657e29_db8 == 1/2),
  (modularWeight d_50e5f4ec_703 == 1/2),
  (modularWeight d_936c26e3_9d6 == 1/2),
  (modularWeight d_1387a909_b1d == 1/2),
  (modularWeight d_de3d7fb0_1c9 == 1/2),
  (modularWeight d_7369d269_b7f == 1/2),
  (modularWeight d_fc8ee452_fe7 == 1/2),
  (modularWeight d_121ae14d_3b0 == 1/2),
  (modularWeight d_6a04ac9a_f92 == 1/2),
  (modularWeight d_c85c4e6f_a1f == 1/2),
  (modularWeight d_7a85eb77_5da == 1/2),
  (modularWeight d_6168297d_9a4 == 1/2),
  (modularWeight d_be8820f4_8b9 == 1/2),
  (modularWeight d_41c80361_060 == 1/2),
  (modularWeight d_3c1aab06_1af == 1/2),
  (modularWeight d_91c74c5b_ce1 == 1/2),
  (modularWeight d_83e58168_c40 == 1/2),
  (modularWeight d_dc54778a_5f2 == 1/2),
  (modularWeight d_85e34eaf_849 == 1/2),
  (modularWeight d_2cb209d2_442 == 1/2),
  (modularWeight d_9cbfe2b9_3a0 == 1/2),
  (modularWeight d_bf272fb0_6f0 == 1/2),
  (modularWeight d_469350b0_bec == 1/2),
  (modularWeight d_ddd6ec45_563 == 1/2),
  (modularWeight d_ea7674a8_ea3 == 1/2),
  (modularWeight d_1cf84b58_cef == 1/2),
  (modularWeight d_17a2edd3_88a == 1/2),
  (modularWeight d_43b8f006_e10 == 1/2),
  (modularWeight d_a07c8df3_6fa == 1/2),
  (modularWeight d_ccde8145_9a4 == 1/2),
  (modularWeight d_ebcfe97c_c1a == 1/2),
  (modularWeight d_593f3788_d1d == 1/2),
  (modularWeight d_e66d6af7_699 == 1/2),
  (modularWeight d_43078c46_6c9 == 1/2),
  (modularWeight d_26d3c458_eab == 1/2),
  (modularWeight d_3228531e_77a == 1/2),
  (modularWeight d_56d94be4_0ee == 1/2),
  (modularWeight d_5e687edc_4af == 1/2),
  (modularWeight d_156b01cc_9ee == 1/2),
  (modularWeight d_2d574c50_dca == 1/2),
  (modularWeight d_9751e15d_591 == 1/2),
  (modularWeight d_68c44b9d_401 == 1/2),
  (modularWeight d_f74df779_0d4 == 1/2),
  (modularWeight d_2bf837ce_46f == 1/2),
  (modularWeight d_eaf90f0c_184 == 1/2),
  (modularWeight d_c37b1b73_f3a == 1/2),
  (modularWeight d_cd9cc228_3ef == 1/2),
  (modularWeight d_e768bbc1_ed1 == 1/2),
  (modularWeight d_e43a0d0c_18d == 1/2),
  (modularWeight d_56e0c99e_f51 == 1/2),
  (modularWeight d_2a5c6f14_c5a == 1/2),
  (modularWeight d_e282a73f_f6e == 1/2),
  (modularWeight d_c0c9506b_f15 == 1/2),
  (modularWeight d_d36e8bab_bbd == 1/2),
  (modularWeight d_31c5b286_2ee == 1/2),
  (modularWeight d_2fc3242e_695 == 1/2),
  (modularWeight d_ca4b1078_339 == 1/2),
  (modularWeight d_480cd210_167 == 1/2),
  (modularWeight d_978bf7f4_a62 == 1/2),
  (modularWeight d_916b04e6_f7f == 1/2),
  (modularWeight d_5101c34d_d92 == 1/2),
  (modularWeight d_a3bb37bb_3d0 == 1/2),
  (modularWeight d_ad0bb270_a8c == 1/2),
  (modularWeight d_b02d427d_9cd == 1/2),
  (modularWeight d_24b8c0b1_c31 == 1/2),
  (modularWeight d_0232e77f_e19 == 1/2),
  (modularWeight d_05e14f40_a08 == 1/2),
  (modularWeight d_d1e19db1_152 == 1/2),
  (modularWeight d_65202556_fff == 1/2),
  (modularWeight d_8f958e6d_d96 == 1/2),
  (modularWeight d_ac221f84_3fe == 1/2),
  (modularWeight d_3853cea6_ffb == 1/2),
  (modularWeight d_e1abc581_918 == 1/2),
  (modularWeight d_713ab765_30e == 1/2),
  (modularWeight d_5762e4f6_781 == 1/2),
  (modularWeight d_7ba0491a_bae == 1/2),
  (modularWeight d_833c932f_8a3 == 1/2),
  (modularWeight d_a38ca17d_3a6 == 1/2),
  (modularWeight d_2b9b8cd8_e32 == 1/2),
  (modularWeight d_11f05b95_da0 == 1/2),
  (modularWeight d_7f3a9e96_a4d == 1/2),
  (modularWeight d_cf8e009e_8a6 == 1/2),
  (modularWeight d_e149994c_1b7 == 1/2),
  (modularWeight d_ee8bfc53_1e7 == 1/2),
  (modularWeight d_4c49578d_c6c == 1/2),
  (modularWeight d_cb3ece0c_9c7 == 1/2),
  (modularWeight d_d48a43c5_e8f == 1/2),
  (modularWeight d_a59d6048_a26 == 1/2),
  (modularWeight d_16942259_7af == 1/2),
  (modularWeight d_05ead7cc_d1b == 1/2),
  (modularWeight d_c1ae1eb3_6da == 1/2),
  (modularWeight d_e8070e9d_658 == 1/2),
  (modularWeight d_b20a8898_c2d == 1/2),
  (modularWeight d_2eb596c1_76b == 1/2),
  (modularWeight d_c7c9cbb9_bd2 == 1/2),
  (modularWeight d_14389dee_afd == 1/2),
  (modularWeight d_c2639eba_aff == 1/2),
  (modularWeight d_3c09010d_5fe == 1/2),
  (modularWeight d_779789f8_1ba == 1/2),
  (modularWeight d_fe629073_18e == 1/2),
  (modularWeight d_fcbc5c1d_011 == 1/2),
  (modularWeight d_738da1de_d60 == 1/2),
  (modularWeight d_be13fe8a_e17 == 1/2),
  (modularWeight d_28f2f792_176 == 1/2),
  (modularWeight d_dbc36c2d_cea == 1/2),
  (modularWeight d_ab56b5b0_529 == 1/2),
  (modularWeight d_5b46ecb4_24a == 1/2),
  (modularWeight d_28ae0216_3bd == 1/2),
  (modularWeight d_ee96fe19_c94 == 1/2),
  (modularWeight d_b2ad728c_870 == 1/2),
  (modularWeight d_9a300e96_463 == 1/2),
  (modularWeight d_604aad88_c56 == 1/2),
  (modularWeight d_1c36bf9c_ec9 == 1/2),
  (modularWeight d_36a88653_e87 == 1/2),
  (modularWeight d_1ffe6879_9f4 == 1/2),
  (modularWeight d_d771521c_e18 == 1/2),
  (modularWeight d_2bc84042_cc1 == 1/2),
  (modularWeight d_ab85b198_0b4 == 1/2),
  (modularWeight d_d3f0b5ad_3d9 == 1/2),
  (modularWeight d_2955c71a_730 == 1/2),
  (modularWeight d_ecea6104_236 == 1/2),
  (modularWeight d_6c58978a_68a == 1/2),
  (modularWeight d_c47e6d86_01b == 1/2),
  (modularWeight d_7422553d_013 == 1/2),
  (modularWeight d_ea67ab28_51a == 1/2),
  (modularWeight d_2601bfa1_bc9 == 1/2),
  (modularWeight d_caaafc30_31c == 1/2),
  (modularWeight d_abee56e2_12d == 1/2),
  (modularWeight d_f5930387_203 == 1/2),
  (modularWeight d_d8a5fcb2_539 == 1/2),
  (modularWeight d_601271d0_71f == 1/2),
  (modularWeight d_b6ab7de8_583 == 1/2),
  (modularWeight d_6dd84ebb_190 == 1/2),
  (modularWeight d_eae7d053_afd == 1/2),
  (modularWeight d_c13a42b5_0c0 == 1/2),
  (modularWeight d_272da95c_451 == 1/2),
  (modularWeight d_5878e976_56a == 1/2),
  (modularWeight d_3a561d69_2b2 == 1/2),
  (modularWeight d_fa611fec_42e == 1/2),
  (modularWeight d_2ce3e943_55b == 1/2),
  (modularWeight d_2e973906_e57 == 1/2),
  (modularWeight d_063b0e2b_e33 == 1/2),
  (modularWeight d_d2cccd53_081 == 1/2),
  (modularWeight d_4751e9b9_480 == 1/2),
  (modularWeight d_a4425044_abd == 1/2),
  (modularWeight d_1886928a_7a4 == 1/2),
  (modularWeight d_f2fedf07_612 == 1/2),
  (modularWeight d_6c93a193_819 == 1/2),
  (modularWeight d_a1967706_dd4 == 1/2),
  (modularWeight d_d7c1e97d_151 == 1/2),
  (modularWeight d_7a0e691a_939 == 1/2),
  (modularWeight d_38b99c9e_c70 == 1/2),
  (modularWeight d_41174f6b_920 == 1/2),
  (modularWeight d_7f966706_aa4 == 1/2),
  (modularWeight d_8a0c5f22_16b == 1/2),
  (modularWeight d_60519e84_a97 == 1/2),
  (modularWeight d_71f281c0_292 == 1/2),
  (modularWeight d_cc9a05a2_3da == 1/2),
  (modularWeight d_a88b88a9_739 == 1/2),
  (modularWeight d_e46131e3_8c2 == 1/2),
  (modularWeight d_470e118c_90c == 1/2),
  (modularWeight d_ec44fec6_592 == 1/2),
  (modularWeight d_07da9cc9_3d2 == 1/2),
  (modularWeight d_d7337903_647 == 1/2),
  (modularWeight d_e4a17dc7_ef5 == 1/2),
  (modularWeight d_311bccdc_edd == 1/2),
  (modularWeight d_d3c24842_896 == 1/2),
  (modularWeight d_51744401_31b == 1/2),
  (modularWeight d_a70892f3_23a == 1/2),
  (modularWeight d_66e6bdcf_3dc == 1/2),
  (modularWeight d_561aa659_c58 == 1/2),
  (modularWeight d_aca03496_813 == 1/2),
  (modularWeight d_2edceaf6_109 == 1/2),
  (modularWeight d_824ea4ae_af0 == 1/2),
  (modularWeight d_08876410_b11 == 1/2),
  (modularWeight d_82ff6f5f_44d == 1/2),
  (modularWeight d_413e94dc_e99 == 1/2),
  (modularWeight d_17013e1a_6b7 == 1/2),
  (modularWeight d_8da8c6c6_b8c == 1/2),
  (modularWeight d_43fb5449_ba0 == 1/2),
  (modularWeight d_eac562fc_8c4 == 1/2),
  (modularWeight d_6145cd1f_816 == 1/2),
  (modularWeight d_28f71c29_340 == 1/2),
  (modularWeight d_39f230d8_eaf == 1/2),
  (modularWeight d_6490b4dd_357 == 1/2),
  (modularWeight d_2a93761e_90d == 1/2),
  (modularWeight d_4d45a487_730 == 1/2),
  (modularWeight d_02a8923e_d49 == 1/2),
  (modularWeight d_5ea9ca0e_7c4 == 1/2),
  (modularWeight d_c335384b_dc7 == 1/2),
  (modularWeight d_c4416eea_8e7 == 1/2),
  (modularWeight d_9521f93b_949 == 1/2),
  (modularWeight d_b19853f3_4ec == 1/2),
  (modularWeight d_0089752e_f99 == 1/2),
  (modularWeight d_5d852da1_55b == 1/2),
  (modularWeight d_eeda8805_7d3 == 1/2),
  (modularWeight d_fb2d3c32_387 == 1/2),
  (modularWeight d_661e7895_fb6 == 1/2),
  (modularWeight d_229db8e1_11a == 1/2),
  (modularWeight d_46b02978_21b == 1/2),
  (modularWeight d_13824e0f_1ea == 1/2),
  (modularWeight d_a554f332_76d == 1/2),
  (modularWeight d_72eeb26a_2f9 == 1/2),
  (modularWeight d_64d1b9ee_e7a == 1/2),
  (modularWeight d_3c518b08_112 == 1/2),
  (modularWeight d_ada2fb6c_85a == 1/2),
  (modularWeight d_909063f4_fe7 == 1/2),
  (modularWeight d_1f29ec52_000 == 1/2),
  (modularWeight d_620fc046_5cf == 1/2),
  (modularWeight d_456b051b_f33 == 1/2),
  (modularWeight d_6e2db9e4_3fa == 1/2),
  (modularWeight d_161f8826_940 == 1/2),
  (modularWeight d_b9d41f53_3b5 == 1/2),
  (modularWeight d_912fe5f9_2c2 == 1/2),
  (modularWeight d_66b7e6cc_195 == 1/2),
  (modularWeight d_12557535_95c == 1/2),
  (modularWeight d_13435407_002 == 1/2),
  (modularWeight d_59d88825_0b2 == 1/2),
  (modularWeight d_2b9b443e_f3c == 1/2),
  (modularWeight d_bfc2b819_be9 == 1/2),
  (modularWeight d_662c4b2f_74b == 1/2),
  (modularWeight d_c8f66120_04f == 1/2),
  (modularWeight d_88421914_08e == 1/2),
  (modularWeight d_3b1db22c_8ac == 1/2),
  (modularWeight d_ba56a556_a09 == 1/2),
  (modularWeight d_e82c2d15_ce3 == 1/2),
  (modularWeight d_f63060d9_b82 == 1/2),
  (modularWeight d_61038119_811 == 1/2),
  (modularWeight d_fdd37ac1_282 == 1/2),
  (modularWeight d_43058a72_2ae == 1/2),
  (modularWeight d_daaf1428_ca6 == 1/2),
  (modularWeight d_2fdf8d88_4d8 == 1/2),
  (modularWeight d_9c868dc7_41c == 1/2),
  (modularWeight d_87d5639a_8c4 == 1/2),
  (modularWeight d_139e195b_e7a == 1/2),
  (modularWeight d_5434cced_159 == 1/2),
  (modularWeight d_d7abcb83_b93 == 1/2),
  (modularWeight d_5ef662a5_e1f == 1/2),
  (modularWeight d_de77ba86_ed2 == 1/2),
  (modularWeight d_b5590ab9_907 == 1/2),
  (modularWeight d_7e6d05f5_f4c == 1/2),
  (modularWeight d_bafda187_98d == 1/2),
  (modularWeight d_a0e67c52_919 == 1/2),
  (modularWeight d_d46437dc_2c6 == 1/2),
  (modularWeight d_320538f1_b66 == 1/2),
  (modularWeight d_a64705d8_fce == 1/2),
  (modularWeight d_55899e83_02e == 1/2),
  (modularWeight d_fd47e986_9f1 == 1/2),
  (modularWeight d_d5cbb0c7_090 == 1/2),
  (modularWeight d_102ce4c0_51b == 1/2),
  (modularWeight d_9f9def2a_8fb == 1/2),
  (modularWeight d_df298c64_1d2 == 1/2),
  (modularWeight d_efa56368_c60 == 1/2),
  (modularWeight d_6e92b84b_8d3 == 1/2),
  (modularWeight d_0dc2f13a_1a6 == 1/2),
  (modularWeight d_aa2a8533_451 == 1/2),
  (modularWeight d_0579e7a2_311 == 1/2),
  (modularWeight d_6369b179_eb0 == 1/2),
  (modularWeight d_3a22fb2b_863 == 1/2),
  (modularWeight d_84329a4c_630 == 1/2),
  (modularWeight d_45f56532_2d1 == 1/2),
  (modularWeight d_661dda4e_dfa == 1/2),
  (modularWeight d_b06b7088_a9c == 1/2),
  (modularWeight d_8e05de4e_df6 == 1/2),
  (modularWeight d_ce7690ac_716 == 1/2),
  (modularWeight d_2f6d69d0_8fc == 1/2),
  (modularWeight d_e459677e_0cb == 1/2),
  (modularWeight d_57ec982a_b5f == 1/2),
  (modularWeight d_eaa67496_39e == 1/2),
  (modularWeight d_9b22946b_329 == 1/2),
  (modularWeight d_6ff86b44_519 == 1/2),
  (modularWeight d_3823f639_815 == 1/2),
  (modularWeight d_7212797d_9b0 == 1/2),
  (modularWeight d_91f5e024_7b5 == 1/2),
  (modularWeight d_b75d5f80_19a == 1/2),
  (modularWeight d_450c24b7_f65 == 1/2),
  (modularWeight d_c1222c51_bef == 1/2),
  (modularWeight d_f211bda0_a30 == 1/2),
  (modularWeight d_16f87864_787 == 1/2),
  (modularWeight d_7306a38a_8fa == 1/2),
  (modularWeight d_b5c26eb3_87d == 1/2),
  (modularWeight d_d26a1079_3ec == 1/2),
  (modularWeight d_15411126_1f7 == 1/2),
  (modularWeight d_e6df2ec0_556 == 1/2),
  (modularWeight d_b4b761a9_9b0 == 1/2),
  (modularWeight d_46a71c1f_819 == 1/2),
  (modularWeight d_d4057cbb_174 == 1/2),
  (modularWeight d_b72a4744_25a == 1/2),
  (modularWeight d_f7efa926_2a0 == 1/2),
  (modularWeight d_9fd8c9dc_028 == 1/2),
  (modularWeight d_ee41b7a3_505 == 1/2),
  (modularWeight d_7934a48e_baf == 1/2),
  (modularWeight d_6699a6f5_e72 == 1/2),
  (modularWeight d_bfc3c544_b6d == 1/2),
  (modularWeight d_7e9d2075_386 == 1/2),
  (modularWeight d_a2db330e_b7b == 1/2),
  (modularWeight d_82fb4068_d98 == 1/2),
  (modularWeight d_27d333b1_6c6 == 1/2),
  (modularWeight d_cc48ac4a_702 == 1/2),
  (modularWeight d_5bd40803_465 == 1/2),
  (modularWeight d_29e22213_e03 == 1/2),
  (modularWeight d_56711609_246 == 1/2),
  (modularWeight d_5e8a0090_3e5 == 1/2),
  (modularWeight d_0b9aaa4a_a8b == 1/2),
  (modularWeight d_5495f618_e36 == 1/2),
  (modularWeight d_59f6c1d6_a94 == 1/2),
  (modularWeight d_5a566fe4_ef3 == 1/2),
  (modularWeight d_206a1b06_b4d == 1/2),
  (modularWeight d_0af33475_a33 == 1/2),
  (modularWeight d_f390afbc_847 == 1/2),
  (modularWeight d_866d2bb5_e30 == 1/2),
  (modularWeight d_41d1f591_512 == 1/2),
  (modularWeight d_c083f2c8_1bb == 1/2),
  (modularWeight d_2dbd8806_542 == 1/2),
  (modularWeight d_283788b4_8e0 == 1/2),
  (modularWeight d_6783c136_2f4 == 1/2),
  (modularWeight d_e3cfd8fd_ae0 == 1/2),
  (modularWeight d_570affc7_02c == 1/2),
  (modularWeight d_f61af7e5_4f5 == 1/2),
  (modularWeight d_4a633f3e_787 == 1/2),
  (modularWeight d_636dfc8e_378 == 1/2),
  (modularWeight d_04c1e69a_cbe == 1/2),
  (modularWeight d_293e100c_362 == 1/2),
  (modularWeight d_4b19a6ec_918 == 1/2),
  (modularWeight d_59d084fa_ad9 == 1/2),
  (modularWeight d_961951d6_f35 == 1/2),
  (modularWeight d_0025c44d_ac5 == 1/2),
  (modularWeight d_f9111d55_e52 == 1/2),
  (modularWeight d_20d71b90_4ba == 1/2),
  (modularWeight d_c2df5b64_aa6 == 1/2),
  (modularWeight d_7ca413c5_560 == 1/2),
  (modularWeight d_21341671_b41 == 1/2),
  (modularWeight d_5e2d860f_a5f == 1/2),
  (modularWeight d_1b232ece_9f1 == 1/2),
  (modularWeight d_1aef7cbe_27a == 1/2),
  (modularWeight d_cb167a96_93d == 1/2),
  (modularWeight d_79ec115a_805 == 1/2),
  (modularWeight d_6a483814_146 == 1/2),
  (modularWeight d_64fce78d_7ac == 1/2),
  (modularWeight d_b1c4e167_0ee == 1/2),
  (modularWeight d_46b132b4_aea == 1/2),
  (modularWeight d_a772e066_7bf == 1/2)
]

#eval checkBatch.length
-- eval outputs number of items, which is 547.
end DualScale.Asymptotics.Batch
