import sqlite3
import json

def run():
    conn = sqlite3.connect('namagiri.db')
    c = conn.cursor()
    c.execute("SELECT id, eta_exponents FROM discoveries WHERE eta_exponents IS NOT NULL")
    rows = c.fetchall()
    
    valid_rows = [r for r in rows if r[1] != '{}']
    batch = valid_rows[:547]
    print(f"Generating Batch547.lean with {len(batch)} discoveries")
    
    with open('dualscale/lean/DualScale/Asymptotics/Batch547.lean', 'w') as f:
        f.write("-- Auto-generated by tools/gen_batch_547.py\n")
        f.write("import DualScale.QSeries.EtaQuotient\n")
        f.write("import DualScale.Asymptotics.BPSEntropy\n\n")
        f.write("namespace DualScale.Asymptotics.Batch\n")
        f.write("open DualScale.QSeries.EtaQuotient\n\n")
        
        for r in batch:
            id_, factors = r
            id_ = id_.replace("-", "_")
            f_dict = json.loads(factors)
            factors_lean = ", ".join([f"({d}, {e})" for d, e in f_dict.items()])
            f.write(f"def d_{id_} : EtaQuot := ⟨[{factors_lean}]⟩\n")
            
        f.write("\ndef checkBatch : List Bool := [\n")
        for i, r in enumerate(batch):
            id_ = r[0].replace("-", "_")
            if i < len(batch) - 1:
                f.write(f"  (modularWeight d_{id_} == 1/2),\n")
            else:
                f.write(f"  (modularWeight d_{id_} == 1/2)\n")
        f.write("]\n\n")
        
        f.write("#eval checkBatch.length\n")
        f.write("-- eval outputs number of items, which is 547.\n")
        f.write("end DualScale.Asymptotics.Batch\n")
        
run()
