import sqlite3
import os
import json

def generate_oeis_submissions(db_path, out_dir):
    conn = sqlite3.connect(db_path)
    c = conn.cursor()
    
    # Fetch novel discoveries suitable for OEIS
    c.execute("SELECT id, archetype, conjecture, rama_energy, andrews_berndt_ref FROM discoveries WHERE is_novel = 1 ORDER BY rama_energy ASC LIMIT 10")
    novel_discoveries = c.fetchall()
    
    os.makedirs(out_dir, exist_ok=True)
    out_file = os.path.join(out_dir, "oeis_batch.txt")
    
    with open(out_file, "w", encoding="utf-8") as f:
        f.write("OEIS BATCH SUBMISSION FILE\n")
        f.write("Generated by RAMA Engine (SocrateAI-Scientific)\n")
        f.write("="*50 + "\n\n")
        
        for idx, disc in enumerate(novel_discoveries, 1):
            id_, arch, conj, energy, ref = disc
            f.write(f"Sequence {idx} (RAMA ID: {id_})\n")
            f.write(f"Name: Sequences related to {arch} modular transformations\n")
            f.write(f"Data: [Placeholder for generated integer sequence from conjecture]\n")
            f.write(f"Formula: Derived from {conj}\n")
            f.write(f"Reference: Andrews-Berndt Vol. Ref: {ref}\n")
            f.write(f"Author: Xavier Callens & RAMA Engine\n")
            f.write("-" * 30 + "\n\n")
            
    print(f"Generated OEIS submission payload at {out_file}")

if __name__ == "__main__":
    generate_oeis_submissions("namagiri.db", "docs/oeis_submission")
